# Predictor-context, privileged-state, backend, and integrated 3P builds.

$(BP_CONTEXT_ALWAYS_BRANCH_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=1 -o $(BP_CONTEXT_ALWAYS_BRANCH_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_NOPREDECODE_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl \
		-Ptb_bp_context.BP_TYPE=1 \
		-Ptb_bp_context.ENABLE_PREDECODE_TARGETS=0 \
		-o $(BP_CONTEXT_NOPREDECODE_SIM_BUILD) \
		$(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_ALWAYS_DECLINE_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=2 -o $(BP_CONTEXT_ALWAYS_DECLINE_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_REPEAT_LAST_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=3 -o $(BP_CONTEXT_REPEAT_LAST_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_BTFNT_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=4 -o $(BP_CONTEXT_BTFNT_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_BIMODAL_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=5 -o $(BP_CONTEXT_BIMODAL_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_GSHARE_BTB_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=6 -o $(BP_CONTEXT_GSHARE_BTB_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_GSHARE_BTB_512_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=7 -o $(BP_CONTEXT_GSHARE_BTB_512_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_TOURNAMENT_BTB_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=8 -o $(BP_CONTEXT_TOURNAMENT_BTB_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_TAGE_BTB_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -Ptb_bp_context.BP_TYPE=9 -o $(BP_CONTEXT_TAGE_BTB_SIM_BUILD) $(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_TAGE_BTB_NOPREDECODE_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl \
		-Ptb_bp_context.BP_TYPE=9 \
		-Ptb_bp_context.ENABLE_PREDECODE_TARGETS=0 \
		-o $(BP_CONTEXT_TAGE_BTB_NOPREDECODE_SIM_BUILD) \
		$(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(BP_CONTEXT_FPGA_QUEUE_SIM_BUILD): $(BP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl \
		-Ptb_bp_context.BP_TYPE=8 \
		-Ptb_bp_context.PIPE_1P_DECODE_QUEUE=1 \
		-o $(BP_CONTEXT_FPGA_QUEUE_SIM_BUILD) \
		$(CORE_SRCS) $(BP_CONTEXT_SIM_SRCS)

$(EXCEPT_SIM_BUILD): $(EXCEPT_SIM_SRCS) $(EXCEPT_SRCS) $(ISA_SRCS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(EXCEPT_SIM_BUILD) $(EXCEPT_SIM_SRCS)

$(EXEC_SYSTEM_CSR_SIM_BUILD): $(EXEC_SYSTEM_CSR_SIM_SRCS) $(EXEC_SRCS) $(ISA_SRCS) $(ARITH_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(EXEC_SYSTEM_CSR_SIM_BUILD) $(EXEC_SYSTEM_CSR_SIM_SRCS)

$(TRAP_CONTEXT_SIM_BUILD): $(TRAP_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(TRAP_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(TRAP_CONTEXT_SIM_SRCS)

$(PRIV_CONTEXT_SIM_BUILD): $(PRIV_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(PRIV_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(PRIV_CONTEXT_SIM_SRCS)

$(IRQ_CONTEXT_SIM_BUILD): $(IRQ_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(IRQ_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(IRQ_CONTEXT_SIM_SRCS)

$(ZICCLSM_CONTEXT_SIM_BUILD): $(ZICCLSM_CONTEXT_SIM_SRCS) $(CORE_SRCS) \
		$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_zicclsm_context \
		-o $(ZICCLSM_CONTEXT_SIM_BUILD) \
		$(CORE_SRCS) $(ZICCLSM_CONTEXT_SIM_SRCS)

$(LOAD_USE_CONTEXT_SIM_BUILD): $(LOAD_USE_CONTEXT_SIM_SRCS) $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl $(LOAD_USE_CONTEXT_IVERILOG_FLAGS) -o $(LOAD_USE_CONTEXT_SIM_BUILD) $(CORE_SRCS) $(LOAD_USE_CONTEXT_SIM_SRCS)

$(REG_OWNER_SIM_BUILD): $(REG_OWNER_SIM_SRCS) rtl/core/dispatch/reg_map.v $(ISA_SRCS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(REG_OWNER_SIM_BUILD) rtl/core/dispatch/reg_map.v $(REG_OWNER_SIM_SRCS)

$(RETIRE_QUEUE_3P_SIM_BUILD): rtl/core/retire/retire_queue_3p.v \
	rtl/core/retire/retire_records_3p.v tb/tb_retire_queue_3p.sv
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(RETIRE_QUEUE_3P_SIM_BUILD) \
		rtl/core/retire/retire_queue_3p.v \
		rtl/core/retire/retire_records_3p.v tb/tb_retire_queue_3p.sv

$(RETIRE_3P_SIM_BUILD): rtl/core/retire/retire_3p.v tb/tb_retire_3p.sv
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(RETIRE_3P_SIM_BUILD) \
		rtl/core/retire/retire_3p.v tb/tb_retire_3p.sv

$(RETIRE_3P_BANKED_SIM_BUILD): rtl/core/retire/retire_3p.v \
		rtl/core/retire/retire_3p_banked.v tb/tb_retire_3p_banked.sv
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_retire_3p_banked \
		-o $(RETIRE_3P_BANKED_SIM_BUILD) \
		rtl/core/retire/retire_3p.v \
		rtl/core/retire/retire_3p_banked.v tb/tb_retire_3p_banked.sv

$(BACKEND_3P_SIM_BUILD): tb/tb_backend_3p.sv $(BACKEND_SRCS) \
	$(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) $(RETIRE_SRCS) \
	$(EXCEPT_SRCS) $(ISA_SRCS) $(ARITH_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_backend_3p -o $(BACKEND_3P_SIM_BUILD) \
		-Ptb_backend_3p.RELAX_HAZARDS=$(BACKEND_3P_RELAX_HAZARDS) \
		-Ptb_backend_3p.PHYS_REG_COUNT=$(BACKEND_3P_PHYS_REG_COUNT) \
		$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
		$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ARITH_DEPS) tb/tb_backend_3p.sv

$(BACKEND_3P_BANKED_SIM_BUILD): tb/tb_backend_3p_banked.sv \
	$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
	$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ISA_SRCS) $(ARITH_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_backend_3p_banked \
		-o $(BACKEND_3P_BANKED_SIM_BUILD) \
		$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
		$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ARITH_DEPS) \
		tb/tb_backend_3p_banked.sv

$(BACKEND_3P_BANKED_TOMASULO_SIM_BUILD): tb/tb_backend_3p_banked.sv \
	$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
	$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ISA_SRCS) $(ARITH_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_backend_3p_banked \
		-Ptb_backend_3p_banked.RENAME_MODE=1 \
		$(BACKEND_3P_BANKED_TOMASULO_IVERILOG_FLAGS) \
		-o $(BACKEND_3P_BANKED_TOMASULO_SIM_BUILD) \
		$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
		$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ARITH_DEPS) \
		tb/tb_backend_3p_banked.sv

$(BACKEND_3P_BANKED_WINDOW_SIM_BUILD): tb/tb_backend_3p_banked.sv \
	$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
	$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ISA_SRCS) $(ARITH_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_backend_3p_banked \
		-Ptb_backend_3p_banked.ISSUE_WINDOW=1 \
		-Ptb_backend_3p_banked.SPECULATION_WINDOW=1 \
		-o $(BACKEND_3P_BANKED_WINDOW_SIM_BUILD) \
		$(BACKEND_SRCS) $(DISPATCH_SRCS) $(REG_SRCS) $(EXEC_SRCS) \
		$(RETIRE_SRCS) $(EXCEPT_SRCS) $(ARITH_DEPS) \
		tb/tb_backend_3p_banked.sv

$(TOP_3P_SIM_BUILD): tb/tb_top_3p.sv rtl/openrv64_top.sv $(CORE_SRCS) \
	$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -o $(TOP_3P_SIM_BUILD) \
		rtl/openrv64_top.sv $(CORE_SRCS) tb/tb_top_3p.sv

$(TOP_3P_BANKED_SIM_BUILD): tb/tb_top_3p_banked.sv \
	rtl/openrv64_top.sv $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl \
		-s tb_top_3p_banked -o $(TOP_3P_BANKED_SIM_BUILD) \
		rtl/openrv64_top.sv $(CORE_SRCS) tb/tb_top_3p_banked.sv

$(TOP_3P_TOMASULO_PMP_SIM_BUILD): tb/tb_top_3p_tomasulo_pmp.sv \
		rtl/openrv64_top.sv $(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl \
		-s tb_top_3p_tomasulo_pmp \
		-o $(TOP_3P_TOMASULO_PMP_SIM_BUILD) \
		rtl/openrv64_top.sv $(CORE_SRCS) tb/tb_top_3p_tomasulo_pmp.sv

$(TOP_4PF_SIM_BUILD): tb/tb_top_4pf.sv $(CORE_4PF_SRCS) \
		$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl $(TOP_4PF_IVERILOG_FLAGS) \
		-s openrv64_top_4pf -s tb_top_4pf \
		-o $(TOP_4PF_SIM_BUILD) $(CORE_4PF_SRCS) tb/tb_top_4pf.sv

$(CORE_3P_MAGIC_VERILATOR_BUILD): tb/tb_core_3p_magic.sv \
		$(CORE_3P_AXI_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(CORE_3P_MAGIC_VERILATOR_DIR)
	$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 0 -Irtl \
		--top-module tb_core_3p_magic \
		-GFETCH_ALT_LOOKASIDE=$(CORE_3P_MAGIC_MODE) \
		-GFETCH_ALT_CONFIDENCE_GATE=$(CORE_3P_MAGIC_CONFIDENCE_GATE) \
		-GBP_TYPE=$(CORE_3P_MAGIC_BP_TYPE) \
		-GCOMPLETION_FORWARD_MASK=$(CORE_3P_MAGIC_COMPLETION_FORWARD_MASK) \
		-GBRANCH_COMPLETION_FORWARD_MASK=$(CORE_3P_MAGIC_BRANCH_FORWARD_MASK) \
		-GENABLE_FULL_FORWARDING=$(CORE_3P_MAGIC_FULL_FORWARDING) \
		-GRELAX_WAW=$(CORE_3P_MAGIC_RELAX_WAW) \
		-GRELAX_HAZARDS=$(CORE_3P_MAGIC_RELAX_HAZARDS) \
		-GRETIRE_DEPTH=$(CORE_3P_MAGIC_RETIRE_DEPTH) \
		-GPHYS_REG_COUNT=$(CORE_3P_MAGIC_PHYS_REG_COUNT) \
		-GRENAME_MODE=$(CORE_3P_MAGIC_RENAME_MODE) \
		-GISSUE_WINDOW=$(CORE_3P_MAGIC_ISSUE_WINDOW) \
		-GSPECULATION_WINDOW=$(CORE_3P_MAGIC_SPECULATION_WINDOW) \
		-GSRAM_BYTES=$(CORE_3P_MAGIC_SRAM_BYTES) \
		--Mdir $(CORE_3P_MAGIC_VERILATOR_DIR) \
		-o core_3p_magic_tb $(CORE_3P_AXI_SRCS) \
		tb/tb_core_3p_magic.sv

$(CORE_3P_ICX_L2_VERILATOR_BUILD): tb/tb_top_3p_soc.v \
		tb/tb_top_3p_soc_tomasulo_trace.vh \
		rtl/core/trace/tomasulo-trace-defs.v \
		$(CORE_3P_AXI_SRCS) $(CORE_COMPLEX_SRCS) \
		$(AXI_DDR3_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(CORE_3P_ICX_L2_VERILATOR_DIR)
	$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 0 -Irtl \
		-DOPENRV64_LSU_TAG_WIDTH=$(CORE_3P_ICX_L2_LSU_TAG_WIDTH) \
		-DOPENRV64_LSU_OUTSTANDING=$(CORE_3P_ICX_L2_LSU_OUTSTANDING) \
		$(if $(filter 1,$(CORE_3P_ICX_L2_STORE_WAVE_TRACE)),--trace-fst --trace-depth 1 -DOPENRV64_SIM_STORE_WAVE) \
		--top-module tb_top_3p_soc \
		-GFETCH_CAROUSEL=$(CORE_3P_ICX_L2_FETCH_CAROUSEL) \
		-GFETCH_ALT_LOOKASIDE=$(CORE_3P_ICX_L2_MODE) \
		-GFETCH_ALT_CONFIDENCE_GATE=$(CORE_3P_ICX_L2_CONFIDENCE_GATE) \
		-GFETCH_ALT_PAIR_STACK_DEPTH=$(CORE_3P_ICX_L2_PAIR_STACK_DEPTH) \
		-GBP_TYPE=$(CORE_3P_ICX_L2_BP_TYPE) \
		-GCOMPLETION_FORWARD_MASK=$(CORE_3P_ICX_L2_COMPLETION_FORWARD_MASK) \
		-GBRANCH_COMPLETION_FORWARD_MASK=$(CORE_3P_ICX_L2_BRANCH_FORWARD_MASK) \
		-GENABLE_FULL_FORWARDING=$(CORE_3P_ICX_L2_FULL_FORWARDING) \
		-GRELAX_WAW=$(CORE_3P_ICX_L2_RELAX_WAW) \
		-GRELAX_HAZARDS=$(CORE_3P_ICX_L2_RELAX_HAZARDS) \
		-GISSUE_WINDOW=$(CORE_3P_ICX_L2_ISSUE_WINDOW) \
		-GSPECULATION_WINDOW=$(CORE_3P_ICX_L2_SPECULATION_WINDOW) \
		-GORACLE_BRANCHES=$(CORE_3P_ICX_L2_ORACLE_BRANCHES) \
		-GBANKED_GPR=$(CORE_3P_ICX_L2_BANKED_GPR) \
		-GFPGA_GPR_LUTRAM=$(CORE_3P_ICX_L2_FPGA_GPR_LUTRAM) \
		-GBANKED_GPR_READ_PORTS_PER_BANK=$(CORE_3P_ICX_L2_BANKED_GPR_READ_PORTS_PER_BANK) \
		-GBANKED_GPR_NUM_BANKS=$(CORE_3P_ICX_L2_BANKED_GPR_NUM_BANKS) \
		-DOPENRV64_3P_RESULT_READY_CONTROL_RELEASE=$(CORE_3P_ICX_L2_RESULT_READY_CONTROL_RELEASE) \
		-GRETIRE_DEPTH=$(CORE_3P_ICX_L2_RETIRE_DEPTH) \
		-GISSUE_WINDOW_DEPTH=$(CORE_3P_ICX_L2_ISSUE_WINDOW_DEPTH) \
		-GPHYS_REG_COUNT=$(CORE_3P_ICX_L2_PHYS_REG_COUNT) \
		-GRENAME_MODE=$(CORE_3P_ICX_L2_RENAME_MODE) \
		-GENABLE_ALU2=$(CORE_3P_ICX_L2_ENABLE_ALU2) \
		-GENABLE_ALU_CHAINING=$(CORE_3P_ICX_L2_ENABLE_ALU_CHAINING) \
		-GENABLE_PIPELINE_STATE_TRACE=$(CORE_3P_ICX_L2_ENABLE_PIPELINE_STATE_TRACE) \
		-GENABLE_POSTED_STORES=$(CORE_3P_ICX_L2_POSTED_STORES) \
		-GSTORE_QUEUE_DEPTH=$(CORE_3P_ICX_L2_STORE_QUEUE_DEPTH) \
		-GENABLE_FENCE_L2_ACK=$(CORE_3P_ICX_L2_FENCE_L2_ACK_ENABLE) \
		-GM_MODE_PREFETCH_ENABLE=$(CORE_3P_ICX_L2_M_MODE_PREFETCH_ENABLE) \
		-GRAM_BYTES=$(CORE_3P_ICX_L2_RAM_BYTES) \
		-GL1I_CACHE_BYTES=$(CORE_3P_ICX_L2_L1I_BYTES) \
		-GL1I_FETCH_DATA_WIDTH=$(CORE_3P_ICX_L2_L1I_FETCH_WIDTH) \
		-GL1D_CACHE_BYTES=$(CORE_3P_ICX_L2_L1D_BYTES) \
		-GL1D_SYNC_TAG_LOOKUP=$(CORE_3P_ICX_L2_L1D_SYNC_TAG_LOOKUP) \
		-GL1D_SYNC_STORE_EXTENSION=$(CORE_3P_ICX_L2_L1D_SYNC_STORE_EXTENSION) \
		-GENABLE_LSU_PAGE_SCREEN=$(CORE_3P_ICX_L2_LSU_PAGE_SCREEN) \
		-GL2_TLB_ENTRIES=$(CORE_3P_ICX_L2_TLB_ENTRIES) \
		-GL2_TLB_WAYS=$(CORE_3P_ICX_L2_TLB_WAYS) \
		-GL2_BYTES=$(CORE_3P_ICX_L2_L2_BYTES) \
		-GL2_WAYS=$(CORE_3P_ICX_L2_L2_WAYS) \
		-GL2_MERGE_ENTRIES=$(CORE_3P_ICX_L2_MSHR_ENTRIES) \
		-GGENBUS_READ_BUFFER_DEPTH=$(CORE_3P_ICX_L2_GENBUS_READ_DEPTH) \
		-GGENBUS_WRITE_BUFFER_DEPTH=$(CORE_3P_ICX_L2_GENBUS_WRITE_DEPTH) \
		-GL1D_PREFETCH_ENABLE=$(CORE_3P_ICX_L2_L1D_PREFETCH_ENABLE) \
		-GL1D_PREFETCH_STREAMS=$(CORE_3P_ICX_L2_L1D_PREFETCH_STREAMS) \
		-GL1D_PREFETCH_DISTANCE=$(CORE_3P_ICX_L2_L1D_PREFETCH_DISTANCE) \
		-GL1D_PREFETCH_ADAPTIVE_ENABLE=$(CORE_3P_ICX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE) \
		-GL1D_PREFETCH_MAX_DISTANCE=$(CORE_3P_ICX_L2_L1D_PREFETCH_MAX_DISTANCE) \
		-GL1D_PREFETCH_QUEUE_LINES=$(CORE_3P_ICX_L2_L1D_PREFETCH_QUEUE_LINES) \
		-GL1D_PREFETCH_OUTSTANDING=$(CORE_3P_ICX_L2_L1D_PREFETCH_OUTSTANDING) \
		-GL1D_PREFETCH_DEMAND_RESERVE=$(CORE_3P_ICX_L2_L1D_PREFETCH_DEMAND_RESERVE) \
		-GL1D_PREFETCH_PAGE_GATING=$(CORE_3P_ICX_L2_L1D_PREFETCH_PAGE_GATING) \
		-GDDR3_ENABLE=$(CORE_3P_ICX_L2_DDR3) \
			-GDDR3_READ_QUEUE_DEPTH=$(CORE_3P_ICX_L2_DDR3_READ_QUEUE_DEPTH) \
			-GDDR3_WRITE_QUEUE_DEPTH=$(CORE_3P_ICX_L2_DDR3_WRITE_QUEUE_DEPTH) \
			-GDDR3_COMMAND_QUEUE_DEPTH=$(CORE_3P_ICX_L2_DDR3_COMMAND_QUEUE_DEPTH) \
			-GDDR3_MAX_BURST_TRAIN_BURSTS=$(CORE_3P_ICX_L2_DDR3_MAX_BURST_TRAIN_BURSTS) \
			-GDDR3_BANK_ROW_SWIZZLE=$(CORE_3P_ICX_L2_DDR3_BANK_ROW_SWIZZLE) \
			-GMEMORY_TIMING_MODEL=$(CORE_3P_ICX_L2_MEMORY_TIMING_MODEL) \
		--Mdir $(CORE_3P_ICX_L2_VERILATOR_DIR) \
		-o core_3p_icx_l2_tb $(CORE_3P_AXI_SRCS) \
		$(CORE_COMPLEX_SRCS) $(AXI_DDR3_SRCS) tb/tb_top_3p_soc.v

$(CORE_4H_3P_VERILATOR_BUILD): tb/tb_4h_3p.sv \
		$(CORE_3P_AXI_SRCS) rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(CORE_4H_3P_VERILATOR_DIR)
	$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 32 \
		--threads $(CORE_4H_3P_VERILATOR_THREADS) -Irtl \
		-GL1D_PREFETCH_ENABLE=$(CORE_4H_3P_L1D_PREFETCH_ENABLE) \
		-GM_MODE_PREFETCH_ENABLE=$(CORE_4H_3P_M_MODE_PREFETCH_ENABLE) \
		-GENABLE_WFI_SLEEP=$(CORE_4H_3P_WFI_SLEEP_ENABLE) \
		-GENABLE_WFI_CLOCK_GATING=$(CORE_4H_3P_WFI_CLOCK_GATING_ENABLE) \
		-GL1D_SYNC_TAG_LOOKUP=$(CORE_4H_3P_L1D_SYNC_TAG_LOOKUP) \
		-GL1D_SYNC_STORE_EXTENSION=$(CORE_4H_3P_L1D_SYNC_STORE_EXTENSION) \
		-GFENCE_L2_ACK_ENABLE=$(CORE_4H_3P_FENCE_L2_ACK_ENABLE) \
		-GSC_EXCLUSIVE_RETAIN_ENABLE=$(CORE_4H_3P_SC_EXCLUSIVE_RETAIN_ENABLE) \
		-GDDR3_ENABLE=$(CORE_4H_3P_DDR3_ENABLE) \
		-GBANKED_GPR=$(CORE_4H_3P_BANKED_GPR) \
		-GFPGA_GPR_LUTRAM=$(CORE_4H_3P_FPGA_GPR_LUTRAM) \
		--output-split 20000 --output-split-cfuncs 2000 \
		--top-module tb_4h_3p \
		--Mdir $(CORE_4H_3P_VERILATOR_DIR) \
		-o core_4h_3p_tb $(CORE_3P_AXI_SRCS) \
		rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		tb/tb_4h_3p.sv

$(CORE_1H_COHERENT_3P_VERILATOR_BUILD): \
		tb/tb_1h_coherent_3p.sv tb/tb_4h_3p.sv \
		$(CORE_3P_AXI_SRCS) rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(CORE_1H_COHERENT_3P_VERILATOR_DIR)
	$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 32 \
		--threads $(CORE_1H_COHERENT_3P_VERILATOR_THREADS) -Irtl \
		-GRETIRE_DEPTH=$(CORE_1H_COHERENT_3P_RETIRE_DEPTH) \
		-GL1D_PREFETCH_ENABLE=$(CORE_4H_3P_L1D_PREFETCH_ENABLE) \
		-GM_MODE_PREFETCH_ENABLE=$(CORE_4H_3P_M_MODE_PREFETCH_ENABLE) \
		-GL1D_SYNC_TAG_LOOKUP=$(CORE_4H_3P_L1D_SYNC_TAG_LOOKUP) \
		-GL1D_SYNC_STORE_EXTENSION=$(CORE_4H_3P_L1D_SYNC_STORE_EXTENSION) \
		-GFENCE_L2_ACK_ENABLE=$(CORE_1H_COHERENT_3P_FENCE_L2_ACK_ENABLE) \
		-GDDR3_ENABLE=1 \
		--output-split 20000 --output-split-cfuncs 2000 \
		--top-module tb_1h_coherent_3p \
		--Mdir $(CORE_1H_COHERENT_3P_VERILATOR_DIR) \
		-o core_1h_coherent_3p_tb \
		rtl/core/decode/defs/early-defs.v $(CORE_3P_AXI_SRCS) \
		rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		tb/tb_4h_3p.sv tb/tb_1h_coherent_3p.sv

$(OPENSBI_4H_HELD_VERILATOR_BUILD): \
		$(OPENSBI_4H_HELD_HARNESS_SOURCE) tb/tb_4h_3p.sv \
		$(CORE_3P_AXI_SRCS) rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(OPENSBI_4H_HELD_VERILATOR_DIR)
	+$(VERILATOR) --binary --timing -Wall -Wno-fatal -j 32 \
		--threads $(OPENSBI_4H_HELD_VERILATOR_THREADS) -Irtl \
		-GCORE_INSTANCES=$(OPENSBI_4H_HELD_CORE_INSTANCES) \
		-GRETIRE_DEPTH=$(OPENSBI_4H_HELD_RETIRE_DEPTH) \
		-GISSUE_WINDOW_DEPTH=$(OPENSBI_4H_HELD_ISSUE_WINDOW_DEPTH) \
		-GPHYS_REG_COUNT=$(OPENSBI_4H_HELD_PHYS_REG_COUNT) \
		-GRENAME_MODE=$(OPENSBI_4H_HELD_RENAME_MODE) \
		-GBANKED_GPR=$(OPENSBI_4H_BANKED_GPR) \
		-GFPGA_GPR_LUTRAM=$(OPENSBI_4H_FPGA_GPR_LUTRAM) \
		-GCOMPLETION_FORWARD_MASK=$(OPENSBI_4H_COMPLETION_FORWARD_MASK) \
		-GBRANCH_COMPLETION_FORWARD_MASK=$(OPENSBI_4H_BRANCH_COMPLETION_FORWARD_MASK) \
		-GRELAX_WAW=$(OPENSBI_4H_RELAX_WAW) \
		-GENABLE_ISSUE_WINDOW=$(OPENSBI_4H_ENABLE_ISSUE_WINDOW) \
		-GENABLE_SPECULATION_WINDOW=$(OPENSBI_4H_ENABLE_SPECULATION_WINDOW) \
		-GFETCH_CAROUSEL=$(OPENSBI_4H_FETCH_CAROUSEL) \
		-GFETCH_ALT_LOOKASIDE=$(OPENSBI_4H_FETCH_ALT_LOOKASIDE) \
		-GFETCH_ALT_CONFIDENCE_GATE=$(OPENSBI_4H_FETCH_ALT_CONFIDENCE_GATE) \
		-GFETCH_ALT_PAIR_STACK_DEPTH=$(OPENSBI_4H_FETCH_ALT_PAIR_STACK_DEPTH) \
		-GFETCH_PAGE_SCREEN_ENTRIES=$(OPENSBI_4H_FETCH_PAGE_SCREEN_ENTRIES) \
		-GLSU_PAGE_SCREEN_ENTRIES=$(OPENSBI_4H_LSU_PAGE_SCREEN_ENTRIES) \
		-GENABLE_RV64ZBB=$(OPENSBI_3P_ENABLE_ZBB) \
		-GENABLE_WFI_SLEEP=$(OPENSBI_4H_WFI_SLEEP_ENABLE) \
		-GENABLE_WFI_CLOCK_GATING=$(OPENSBI_4H_WFI_CLOCK_GATING_ENABLE) \
		-GFENCE_L2_ACK_ENABLE=$(OPENSBI_4H_FENCE_L2_ACK_ENABLE) \
		-GL1D_PREFETCH_ENABLE=$(CORE_4H_3P_L1D_PREFETCH_ENABLE) \
		-GM_MODE_PREFETCH_ENABLE=$(CORE_4H_3P_M_MODE_PREFETCH_ENABLE) \
		-GL1D_SYNC_TAG_LOOKUP=$(CORE_4H_3P_L1D_SYNC_TAG_LOOKUP) \
		-GL1D_SYNC_STORE_EXTENSION=$(CORE_4H_3P_L1D_SYNC_STORE_EXTENSION) \
		-GMEMORY_BYTES=$(OPENSBI_4H_HELD_MEMORY_BYTES) \
		-GENABLE_BOOT_ROM=1 \
		-GOPENSBI_FDT_BASE_LO=$(OPENSBI_4H_HELD_FDT_BASE) \
		-GDDR3_ENABLE=$(OPENSBI_4H_DDR3_ENABLE) \
		-GGENBUS_READ_BUFFER_DEPTH=$(OPENSBI_4H_GENBUS_READ_DEPTH) \
		-GGENBUS_WRITE_BUFFER_DEPTH=$(OPENSBI_4H_GENBUS_WRITE_DEPTH) \
		-GDDR3_READ_QUEUE_DEPTH=$(OPENSBI_4H_DDR3_READ_QUEUE_DEPTH) \
		-GDDR3_WRITE_QUEUE_DEPTH=$(OPENSBI_4H_DDR3_WRITE_QUEUE_DEPTH) \
		-GDDR3_COMMAND_QUEUE_DEPTH=$(OPENSBI_4H_DDR3_COMMAND_QUEUE_DEPTH) \
		-GDDR3_MAX_BURST_TRAIN_BURSTS=$(OPENSBI_4H_DDR3_MAX_BURST_TRAIN_BURSTS) \
		-GDDR3_BANK_ROW_SWIZZLE=$(OPENSBI_4H_DDR3_BANK_ROW_SWIZZLE) \
		--output-split 20000 --output-split-cfuncs 2000 \
		--top-module tb_4h_3p \
		--Mdir $(OPENSBI_4H_HELD_VERILATOR_DIR) \
		-o opensbi_4h_held_tb $(CORE_3P_AXI_SRCS) \
		rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		$(OPENSBI_4H_HELD_HARNESS_SOURCE)

$(OPENSBI_4H_HELD_CHECKPOINT_VERILATOR_BUILD): \
		tb/verilator_4h_checkpoint_main.cpp \
		$(OPENSBI_4H_HELD_HARNESS_SOURCE) tb/tb_4h_3p.sv \
		$(CORE_3P_AXI_SRCS) rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		$(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS)
	mkdir -p $(OPENSBI_4H_HELD_CHECKPOINT_VERILATOR_DIR)
	+$(VERILATOR) --cc --exe --build --no-timing --savable \
		-Wall -Wno-fatal -j 32 \
		--threads $(OPENSBI_4H_HELD_VERILATOR_THREADS) -Irtl \
		-DOPENRV64_4H_VERILATOR_CHECKPOINT \
		-CFLAGS "-DOPENRV64_4H_CORE_INSTANCES=$(OPENSBI_4H_HELD_CORE_INSTANCES)" \
		-GCORE_INSTANCES=$(OPENSBI_4H_HELD_CORE_INSTANCES) \
		-GRETIRE_DEPTH=$(OPENSBI_4H_HELD_RETIRE_DEPTH) \
		-GISSUE_WINDOW_DEPTH=$(OPENSBI_4H_HELD_ISSUE_WINDOW_DEPTH) \
		-GPHYS_REG_COUNT=$(OPENSBI_4H_HELD_PHYS_REG_COUNT) \
		-GRENAME_MODE=$(OPENSBI_4H_HELD_RENAME_MODE) \
		-GBANKED_GPR=$(OPENSBI_4H_BANKED_GPR) \
		-GFPGA_GPR_LUTRAM=$(OPENSBI_4H_FPGA_GPR_LUTRAM) \
		-GCOMPLETION_FORWARD_MASK=$(OPENSBI_4H_COMPLETION_FORWARD_MASK) \
		-GBRANCH_COMPLETION_FORWARD_MASK=$(OPENSBI_4H_BRANCH_COMPLETION_FORWARD_MASK) \
		-GRELAX_WAW=$(OPENSBI_4H_RELAX_WAW) \
		-GENABLE_ISSUE_WINDOW=$(OPENSBI_4H_ENABLE_ISSUE_WINDOW) \
		-GENABLE_SPECULATION_WINDOW=$(OPENSBI_4H_ENABLE_SPECULATION_WINDOW) \
		-GFETCH_CAROUSEL=$(OPENSBI_4H_FETCH_CAROUSEL) \
		-GFETCH_ALT_LOOKASIDE=$(OPENSBI_4H_FETCH_ALT_LOOKASIDE) \
		-GFETCH_ALT_CONFIDENCE_GATE=$(OPENSBI_4H_FETCH_ALT_CONFIDENCE_GATE) \
		-GFETCH_ALT_PAIR_STACK_DEPTH=$(OPENSBI_4H_FETCH_ALT_PAIR_STACK_DEPTH) \
		-GFETCH_PAGE_SCREEN_ENTRIES=$(OPENSBI_4H_FETCH_PAGE_SCREEN_ENTRIES) \
		-GLSU_PAGE_SCREEN_ENTRIES=$(OPENSBI_4H_LSU_PAGE_SCREEN_ENTRIES) \
		-GENABLE_RV64ZBB=$(OPENSBI_3P_ENABLE_ZBB) \
		-GENABLE_WFI_SLEEP=$(OPENSBI_4H_WFI_SLEEP_ENABLE) \
		-GENABLE_WFI_CLOCK_GATING=$(OPENSBI_4H_WFI_CLOCK_GATING_ENABLE) \
		-GFENCE_L2_ACK_ENABLE=$(OPENSBI_4H_FENCE_L2_ACK_ENABLE) \
		-GL1D_PREFETCH_ENABLE=$(CORE_4H_3P_L1D_PREFETCH_ENABLE) \
		-GM_MODE_PREFETCH_ENABLE=$(CORE_4H_3P_M_MODE_PREFETCH_ENABLE) \
		-GL1D_SYNC_TAG_LOOKUP=$(CORE_4H_3P_L1D_SYNC_TAG_LOOKUP) \
		-GL1D_SYNC_STORE_EXTENSION=$(CORE_4H_3P_L1D_SYNC_STORE_EXTENSION) \
		-GMEMORY_BYTES=$(OPENSBI_4H_HELD_MEMORY_BYTES) \
		-GENABLE_BOOT_ROM=1 \
		-GOPENSBI_FDT_BASE_LO=$(OPENSBI_4H_HELD_FDT_BASE) \
		-GDDR3_ENABLE=$(OPENSBI_4H_DDR3_ENABLE) \
		-GGENBUS_READ_BUFFER_DEPTH=$(OPENSBI_4H_GENBUS_READ_DEPTH) \
		-GGENBUS_WRITE_BUFFER_DEPTH=$(OPENSBI_4H_GENBUS_WRITE_DEPTH) \
		-GDDR3_READ_QUEUE_DEPTH=$(OPENSBI_4H_DDR3_READ_QUEUE_DEPTH) \
		-GDDR3_WRITE_QUEUE_DEPTH=$(OPENSBI_4H_DDR3_WRITE_QUEUE_DEPTH) \
		-GDDR3_COMMAND_QUEUE_DEPTH=$(OPENSBI_4H_DDR3_COMMAND_QUEUE_DEPTH) \
		-GDDR3_MAX_BURST_TRAIN_BURSTS=$(OPENSBI_4H_DDR3_MAX_BURST_TRAIN_BURSTS) \
		-GDDR3_BANK_ROW_SWIZZLE=$(OPENSBI_4H_DDR3_BANK_ROW_SWIZZLE) \
		--output-split 20000 --output-split-cfuncs 2000 \
		--top-module tb_4h_3p \
		--Mdir $(OPENSBI_4H_HELD_CHECKPOINT_VERILATOR_DIR) \
		-o opensbi_4h_checkpoint_tb \
		$(abspath tb/verilator_4h_checkpoint_main.cpp) \
		$(CORE_3P_AXI_SRCS) \
		rtl/complex/protocol/line_crossbar.v \
		$(ICX_L2_SRCS) $(ICX_COHERENT_SRCS) \
		$(COMPLEX_BUS_SRCS) $(AXI_DDR3_SRCS) \
		$(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) $(UART_SRCS) \
		$(OPENSBI_4H_HELD_HARNESS_SOURCE)

$(TOP_AXI_3P_SIM_BUILD): tb/tb_top_axi_3p.sv rtl/openrv64_top_3p.v \
	$(CORE_SRCS) $(ISA_SRCS) $(ARITH_DEPS) $(BP_DEPS) \
	$(SOC_BUS_SRCS) $(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) \
	$(UART_SRCS) $(GPIO_SRCS) $(TIMER_SRCS)
	mkdir -p sim
	iverilog -g2012 -Wall -Irtl -s tb_top_axi_3p \
		-Ptb_top_axi_3p.RAM_BYTES=16777216 \
		-Ptb_top_axi_3p.BP_TYPE=$(AXI_3P_BP_TYPE) \
		-Ptb_top_axi_3p.BP_RAS_ENABLE=$(AXI_3P_BP_RAS_ENABLE) \
		-Ptb_top_axi_3p.BP_RAS_DEPTH=$(AXI_3P_BP_RAS_DEPTH) \
		-Ptb_top_axi_3p.BP_BIMODAL_ENTRIES=$(AXI_3P_BP_BIMODAL_ENTRIES) \
		-Ptb_top_axi_3p.BP_BIMODAL_COUNTER_BITS=$(AXI_3P_BP_BIMODAL_COUNTER_BITS) \
		-Ptb_top_axi_3p.BP_BIMODAL_UPDATE_DEPTH=$(AXI_3P_BP_BIMODAL_UPDATE_DEPTH) \
		-Ptb_top_axi_3p.BP_GSHARE_ENTRIES=$(AXI_3P_BP_GSHARE_ENTRIES) \
		-Ptb_top_axi_3p.BP_GSHARE_COUNTER_BITS=$(AXI_3P_BP_GSHARE_COUNTER_BITS) \
		-Ptb_top_axi_3p.BP_BTB_ENTRIES=$(AXI_3P_BP_BTB_ENTRIES) \
		-Ptb_top_axi_3p.BP_BTB_TAG_BITS=$(AXI_3P_BP_BTB_TAG_BITS) \
		-Ptb_top_axi_3p.BP_INFLIGHT_DEPTH=$(AXI_3P_BP_INFLIGHT_DEPTH) \
		-Ptb_top_axi_3p.RETIRE_DEPTH=$(AXI_3P_RETIRE_DEPTH) \
		-Ptb_top_axi_3p.PHYS_REG_COUNT=$(AXI_3P_PHYS_REG_COUNT) \
		-Ptb_top_axi_3p.COMPLETION_FORWARD_MASK=$(AXI_3P_COMPLETION_FORWARD_MASK) \
		-Ptb_top_axi_3p.BRANCH_FORWARD_MASK=$(AXI_3P_BRANCH_FORWARD_MASK) \
		-Ptb_top_axi_3p.FULL_FORWARDING=$(AXI_3P_FULL_FORWARDING) \
		-Ptb_top_axi_3p.RELAX_WAW=$(AXI_3P_RELAX_WAW) \
		-Ptb_top_axi_3p.RELAX_HAZARDS=$(AXI_3P_RELAX_HAZARDS) \
		-Ptb_top_axi_3p.ISSUE_WINDOW=$(AXI_3P_ISSUE_WINDOW) \
		-Ptb_top_axi_3p.SPECULATION_WINDOW=$(AXI_3P_SPECULATION_WINDOW) \
		-Ptb_top_axi_3p.POSTED_STORES=$(AXI_3P_POSTED_STORES) \
		-Ptb_top_axi_3p.FREE_BRANCHES=$(AXI_3P_FREE_BRANCHES) \
		-Ptb_top_axi_3p.EQ_BRANCH_PAIRING=$(AXI_3P_EQ_BRANCH_PAIRING) \
		-Ptb_top_axi_3p.ORACLE_BRANCHES=$(AXI_3P_ORACLE_BRANCHES) \
		-Ptb_top_axi_3p.FREE_L1_REFILLS=$(AXI_3P_FREE_L1_REFILLS) \
		-Ptb_top_axi_3p.FREE_L1I_REFILLS=$(AXI_3P_FREE_L1I_REFILLS) \
		-Ptb_top_axi_3p.FREE_L1D_REFILLS=$(AXI_3P_FREE_L1D_REFILLS) \
		-Ptb_top_axi_3p.FREELOADER=$(AXI_3P_FREELOADER) \
		-Ptb_top_axi_3p.FREELOADER_LATENCY=$(AXI_3P_FREELOADER_LATENCY) \
		-Ptb_top_axi_3p.L1D_PREFETCH_ENABLE=$(AXI_3P_L1D_PREFETCH_ENABLE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_MAX_STRIDE_LINES=$(AXI_3P_L1D_PREFETCH_MAX_STRIDE_LINES) \
		-Ptb_top_axi_3p.L1D_PREFETCH_STREAMS=$(AXI_3P_L1D_PREFETCH_STREAMS) \
		-Ptb_top_axi_3p.L1D_PREFETCH_DISTANCE=$(AXI_3P_L1D_PREFETCH_DISTANCE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_ADAPTIVE_ENABLE=$(AXI_3P_L1D_PREFETCH_ADAPTIVE_ENABLE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_MAX_DISTANCE=$(AXI_3P_L1D_PREFETCH_MAX_DISTANCE) \
		-Ptb_top_axi_3p.L1D_PREFETCH_QUEUE_LINES=$(AXI_3P_L1D_PREFETCH_QUEUE_LINES) \
		-Ptb_top_axi_3p.L1D_PREFETCH_OUTSTANDING=$(AXI_3P_L1D_PREFETCH_OUTSTANDING) \
		-Ptb_top_axi_3p.L1D_PREFETCH_DEMAND_RESERVE=$(AXI_3P_L1D_PREFETCH_DEMAND_RESERVE) \
		-Ptb_top_axi_3p.FETCH_ALT_LOOKASIDE=$(AXI_3P_FETCH_ALT_LOOKASIDE) \
		-Ptb_top_axi_3p.FETCH_ALT_CONFIDENCE_GATE=$(AXI_3P_FETCH_ALT_CONFIDENCE_GATE) \
		-o $(TOP_AXI_3P_SIM_BUILD) rtl/openrv64_top_3p.v $(CORE_SRCS) \
		$(SOC_BUS_SRCS) $(ROM_SRCS) $(CLINT_SRCS) $(PLIC_SRCS) \
		$(UART_SRCS) $(GPIO_SRCS) $(TIMER_SRCS) \
		tb/tb_top_axi_3p.sv
