# Linux generic BLAKE2s compression microbenchmark.

BLAKE2S_CALLS ?= 16
BLAKE2S_BLOCKS_PER_CALL ?= 1

ifeq ($(filter $(BLAKE2S_CALLS),1 4 16 64),)
$(error BLAKE2S_CALLS must be 1, 4, 16, or 64)
endif
ifeq ($(filter $(BLAKE2S_BLOCKS_PER_CALL),1 2 4 8 16),)
$(error BLAKE2S_BLOCKS_PER_CALL must be 1, 2, 4, 8, or 16)
endif

BLAKE2S_TAG := c$(BLAKE2S_CALLS)-b$(BLAKE2S_BLOCKS_PER_CALL)
BLAKE2S_BUILD_DIR := build/blake2s/$(BLAKE2S_TAG)
BLAKE2S_ELF := $(BLAKE2S_BUILD_DIR)/blake2s.elf
BLAKE2S_BIN := $(BLAKE2S_BUILD_DIR)/blake2s.bin
BLAKE2S_MEMH := $(BLAKE2S_BUILD_DIR)/blake2s.memh
BLAKE2S_MAP := $(BLAKE2S_BUILD_DIR)/blake2s.map
BLAKE2S_DISASM := $(BLAKE2S_BUILD_DIR)/blake2s.disasm
BLAKE2S_IMAGE_BYTES := 131072
BLAKE2S_MEMH_WORDS := 4096
BLAKE2S_MAX_CYCLES ?= 2000000
BLAKE2S_PROGRESS_CYCLES ?= 250000
BLAKE2S_PASS := 424c414b45324f4b
BLAKE2S_DDR3 ?= 0
BLAKE2S_MEMORY_TIMING_MODEL ?= 0
BLAKE2S_DDR3_BANK_ROW_SWIZZLE ?= 0
BLAKE2S_REQUIRE_ARGS ?=
BLAKE2S_MEASURE_END = $(shell $(RISCV_NM) -n $(BLAKE2S_ELF) | \
	awk '$$3 == "blake2s_measure_end" { print $$1 }')
BLAKE2S_COMPRESS_SIZE = $(shell $(RISCV_NM) -S --size-sort \
	$(BLAKE2S_ELF) | awk '$$4 == "blake2s_compress_generic" { print $$2 }')

.PHONY: sw-blake2s sim-blake2s sim-blake2s-ddr3 \
	bench-blake2s bench-blake2s-ddr3

$(BLAKE2S_ELF): $(OPENRV64_MAKEFILES) \
		sw/blake2s/blake2s_start.S sw/blake2s/blake2s.c sw/openrv64.ld
	mkdir -p $(dir $@)
	$(RISCV_CC) $(PREFETCH_CFLAGS) -fno-strict-overflow \
		-fconserve-stack -mstrict-align -nostdlib -nostartfiles \
		-DBLAKE2S_BENCH_CALLS=$(BLAKE2S_CALLS) \
		-DBLAKE2S_BLOCKS_PER_CALL=$(BLAKE2S_BLOCKS_PER_CALL) \
		-Wl,--build-id=none,-Map,$(BLAKE2S_MAP) \
		-T sw/openrv64.ld -o $@ \
		sw/blake2s/blake2s_start.S sw/blake2s/blake2s.c

$(BLAKE2S_BIN): $(BLAKE2S_ELF)
	$(RISCV_OBJCOPY) -O binary $< $@

$(BLAKE2S_MEMH): $(BLAKE2S_BIN) tools/bin2mem.py
	$(PYTHON) tools/bin2mem.py $< $@ \
		--size $(BLAKE2S_IMAGE_BYTES) --word-bytes 32

$(BLAKE2S_DISASM): $(BLAKE2S_ELF)
	$(RISCV_OBJDUMP) -d -S -M no-aliases $< > $@

sw-blake2s: $(BLAKE2S_ELF) $(BLAKE2S_BIN) $(BLAKE2S_MEMH) \
		$(BLAKE2S_DISASM)
	@echo "BLAKE2s generic compression size: 0x$(BLAKE2S_COMPRESS_SIZE) bytes"

sim-blake2s: $(BLAKE2S_MEMH)
	$(MAKE) sim-core-3p-icx-l2 \
		CORE_3P_ICX_L2_MEMH=$(BLAKE2S_MEMH) \
		CORE_3P_ICX_L2_MEMH_WORDS=$(BLAKE2S_MEMH_WORDS) \
		CORE_3P_ICX_L2_ARGS="+expect_a0=$(BLAKE2S_PASS) +progress_cycles=$(BLAKE2S_PROGRESS_CYCLES) $(BLAKE2S_REQUIRE_ARGS)" \
		CORE_3P_ICX_L2_MAX_CYCLES=$(BLAKE2S_MAX_CYCLES) \
		CORE_3P_ICX_L2_RAM_BYTES=16777216 \
		CORE_3P_ICX_L2_BP_TYPE=8 \
		CORE_3P_ICX_L2_FETCH_CAROUSEL=1 \
		CORE_3P_ICX_L2_MODE=3 \
		CORE_3P_ICX_L2_CONFIDENCE_GATE=0 \
		CORE_3P_ICX_L2_RETIRE_DEPTH=32 \
		CORE_3P_ICX_L2_PHYS_REG_COUNT=31 \
		CORE_3P_ICX_L2_ISSUE_WINDOW=1 \
		CORE_3P_ICX_L2_SPECULATION_WINDOW=1 \
		CORE_3P_ICX_L2_POSTED_STORES=1 \
		CORE_3P_ICX_L2_L1D_PREFETCH_ENABLE=1 \
		CORE_3P_ICX_L2_DDR3=$(BLAKE2S_DDR3) \
		CORE_3P_ICX_L2_DDR3_BANK_ROW_SWIZZLE=$(BLAKE2S_DDR3_BANK_ROW_SWIZZLE) \
		CORE_3P_ICX_L2_MEMORY_TIMING_MODEL=$(BLAKE2S_MEMORY_TIMING_MODEL)

bench-blake2s: $(BLAKE2S_MEMH)
	test -n "$(BLAKE2S_MEASURE_END)"
	$(MAKE) sim-core-3p-icx-l2 \
		CORE_3P_ICX_L2_MEMH=$(BLAKE2S_MEMH) \
		CORE_3P_ICX_L2_MEMH_WORDS=$(BLAKE2S_MEMH_WORDS) \
		CORE_3P_ICX_L2_ARGS="+done_pc=$(BLAKE2S_MEASURE_END) +report_blake2s +progress_cycles=$(BLAKE2S_PROGRESS_CYCLES) $(BLAKE2S_REQUIRE_ARGS)" \
		CORE_3P_ICX_L2_MAX_CYCLES=$(BLAKE2S_MAX_CYCLES) \
		CORE_3P_ICX_L2_RAM_BYTES=16777216 \
		CORE_3P_ICX_L2_BP_TYPE=8 \
		CORE_3P_ICX_L2_FETCH_CAROUSEL=1 \
		CORE_3P_ICX_L2_MODE=3 \
		CORE_3P_ICX_L2_CONFIDENCE_GATE=0 \
		CORE_3P_ICX_L2_RETIRE_DEPTH=32 \
		CORE_3P_ICX_L2_PHYS_REG_COUNT=31 \
		CORE_3P_ICX_L2_ISSUE_WINDOW=1 \
		CORE_3P_ICX_L2_SPECULATION_WINDOW=1 \
		CORE_3P_ICX_L2_POSTED_STORES=1 \
		CORE_3P_ICX_L2_L1D_PREFETCH_ENABLE=1 \
		CORE_3P_ICX_L2_DDR3=$(BLAKE2S_DDR3) \
		CORE_3P_ICX_L2_DDR3_BANK_ROW_SWIZZLE=$(BLAKE2S_DDR3_BANK_ROW_SWIZZLE) \
		CORE_3P_ICX_L2_MEMORY_TIMING_MODEL=$(BLAKE2S_MEMORY_TIMING_MODEL)

sim-blake2s-ddr3:
	$(MAKE) sim-blake2s BLAKE2S_DDR3=1 \
		BLAKE2S_REQUIRE_ARGS=+require_timed_memory

bench-blake2s-ddr3:
	$(MAKE) bench-blake2s BLAKE2S_DDR3=1 \
		BLAKE2S_REQUIRE_ARGS=+require_timed_memory
