# Three-pipe performance and parameter-sweep workflows.

sim-top-axi-3p-bp:
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=0
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=1
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=2
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=3
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=4
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=5
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=6
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=7
	$(MAKE) -B sim-top-axi-3p AXI_3P_BP_TYPE=8

sim-top-axi-3p-perf: $(AXI_3P_PERF_MEMH)
	$(MAKE) -B $(TOP_AXI_3P_SIM_BUILD) \
		AXI_3P_BP_TYPE=$(AXI_3P_PERF_BP_TYPE) \
		AXI_3P_BP_RAS_ENABLE=$(AXI_3P_PERF_BP_RAS_ENABLE) \
		AXI_3P_BP_RAS_DEPTH=$(AXI_3P_PERF_BP_RAS_DEPTH) \
		AXI_3P_BP_BIMODAL_ENTRIES=$(AXI_3P_PERF_BP_BIMODAL_ENTRIES) \
		AXI_3P_BP_BIMODAL_COUNTER_BITS=$(AXI_3P_PERF_BP_BIMODAL_COUNTER_BITS) \
		AXI_3P_BP_BIMODAL_UPDATE_DEPTH=$(AXI_3P_PERF_BP_BIMODAL_UPDATE_DEPTH) \
		AXI_3P_BP_GSHARE_ENTRIES=$(AXI_3P_PERF_BP_GSHARE_ENTRIES) \
		AXI_3P_BP_GSHARE_COUNTER_BITS=$(AXI_3P_PERF_BP_GSHARE_COUNTER_BITS) \
		AXI_3P_BP_BTB_ENTRIES=$(AXI_3P_PERF_BP_BTB_ENTRIES) \
		AXI_3P_BP_BTB_TAG_BITS=$(AXI_3P_PERF_BP_BTB_TAG_BITS) \
		AXI_3P_BP_INFLIGHT_DEPTH=$(AXI_3P_PERF_BP_INFLIGHT_DEPTH) \
		AXI_3P_RETIRE_DEPTH=$(AXI_3P_RETIRE_DEPTH) \
		AXI_3P_COMPLETION_FORWARD_MASK=$(AXI_3P_COMPLETION_FORWARD_MASK) \
		AXI_3P_BRANCH_FORWARD_MASK=$(AXI_3P_BRANCH_FORWARD_MASK) \
		AXI_3P_FULL_FORWARDING=$(AXI_3P_FULL_FORWARDING) \
		AXI_3P_RELAX_WAW=$(AXI_3P_RELAX_WAW) \
		AXI_3P_RELAX_HAZARDS=$(AXI_3P_RELAX_HAZARDS) \
		AXI_3P_ISSUE_WINDOW=$(AXI_3P_ISSUE_WINDOW) \
		AXI_3P_SPECULATION_WINDOW=$(AXI_3P_SPECULATION_WINDOW) \
		AXI_3P_POSTED_STORES=$(AXI_3P_POSTED_STORES) \
		AXI_3P_FREE_BRANCHES=$(AXI_3P_FREE_BRANCHES) \
		AXI_3P_EQ_BRANCH_PAIRING=$(AXI_3P_EQ_BRANCH_PAIRING) \
		AXI_3P_ORACLE_BRANCHES=$(AXI_3P_ORACLE_BRANCHES) \
		AXI_3P_FREE_L1_REFILLS=$(AXI_3P_FREE_L1_REFILLS) \
		AXI_3P_FREE_L1I_REFILLS=$(AXI_3P_FREE_L1I_REFILLS) \
		AXI_3P_FREE_L1D_REFILLS=$(AXI_3P_FREE_L1D_REFILLS) \
		AXI_3P_FREELOADER=$(AXI_3P_FREELOADER) \
		AXI_3P_FREELOADER_LATENCY=$(AXI_3P_FREELOADER_LATENCY) \
		AXI_3P_L1D_PREFETCH_ENABLE=$(AXI_3P_PERF_L1D_PREFETCH_ENABLE) \
		AXI_3P_L1D_PREFETCH_MAX_STRIDE_LINES=$(AXI_3P_PERF_L1D_PREFETCH_MAX_STRIDE_LINES) \
		AXI_3P_L1D_PREFETCH_STREAMS=$(AXI_3P_PERF_L1D_PREFETCH_STREAMS) \
		AXI_3P_L1D_PREFETCH_DISTANCE=$(AXI_3P_PERF_L1D_PREFETCH_DISTANCE) \
		AXI_3P_L1D_PREFETCH_ADAPTIVE_ENABLE=$(AXI_3P_PERF_L1D_PREFETCH_ADAPTIVE_ENABLE) \
		AXI_3P_L1D_PREFETCH_MAX_DISTANCE=$(AXI_3P_PERF_L1D_PREFETCH_MAX_DISTANCE) \
		AXI_3P_L1D_PREFETCH_QUEUE_LINES=$(AXI_3P_PERF_L1D_PREFETCH_QUEUE_LINES) \
		AXI_3P_L1D_PREFETCH_OUTSTANDING=$(AXI_3P_PERF_L1D_PREFETCH_OUTSTANDING) \
		AXI_3P_L1D_PREFETCH_DEMAND_RESERVE=$(AXI_3P_PERF_L1D_PREFETCH_DEMAND_RESERVE) \
		AXI_3P_FETCH_ALT_LOOKASIDE=$(AXI_3P_FETCH_ALT_LOOKASIDE) \
		AXI_3P_FETCH_ALT_CONFIDENCE_GATE=$(AXI_3P_FETCH_ALT_CONFIDENCE_GATE)
	mkdir -p $(dir $(AXI_3P_TRACE_CSV)) $(dir $(AXI_3P_TRACE_REPORT))
ifeq ($(AXI_3P_PERF_PIPELINE_TRACE),1)
	vvp $(TOP_AXI_3P_SIM_BUILD) +memh=$(AXI_3P_PERF_MEMH) \
		+max_cycles=$(AXI_3P_PERF_MAX_CYCLES) $(AXI_3P_PERF_ARGS) \
		+pipeline_trace=$(AXI_3P_TRACE_CSV)
	$(PYTHON) tools/pipeline_trace_3p.py $(AXI_3P_TRACE_CSV) \
		--output $(AXI_3P_TRACE_REPORT) $(AXI_3P_TRACE_RENDER_ARGS)
	@echo "raw 3P trace: $(AXI_3P_TRACE_CSV)"
	@echo "3P pipeline report: $(AXI_3P_TRACE_REPORT)"
else
	vvp $(TOP_AXI_3P_SIM_BUILD) +memh=$(AXI_3P_PERF_MEMH) \
		+max_cycles=$(AXI_3P_PERF_MAX_CYCLES) $(AXI_3P_PERF_ARGS) \
		+no_pipeline_trace
endif
