# Google Multi-Chase-derived dependent-load latency workload.

POINTER_CHASE_BYTES ?= 16777216
POINTER_CHASE_STRIDE ?= 256
POINTER_CHASE_TLB_LOCALITY ?= 262144
POINTER_CHASE_STEPS ?= 131072
POINTER_CHASE_SEED ?= 1
POINTER_CHASE_NODES := $(shell expr $(POINTER_CHASE_BYTES) / $(POINTER_CHASE_STRIDE))
POINTER_CHASE_TAG := $(POINTER_CHASE_BYTES)-s$(POINTER_CHASE_STRIDE)-tlb$(POINTER_CHASE_TLB_LOCALITY)-n$(POINTER_CHASE_STEPS)-seed$(POINTER_CHASE_SEED)
POINTER_CHASE_RING_S := build/generated/pointer-chase-ring-$(POINTER_CHASE_TAG).S
POINTER_CHASE_ELF := sw/multichase/pointer-chase-$(POINTER_CHASE_TAG).elf
POINTER_CHASE_BIN := sw/multichase/pointer-chase-$(POINTER_CHASE_TAG).bin
POINTER_CHASE_MAP := sw/multichase/pointer-chase-$(POINTER_CHASE_TAG).map
POINTER_CHASE_DISASM := sw/multichase/pointer-chase-$(POINTER_CHASE_TAG).disasm
POINTER_CHASE_MEASURE_END = $(shell $(RISCV_NM) -n $(POINTER_CHASE_ELF) | \
	awk '$$3 == "pointer_chase_measure_end" { print $$1 }')
POINTER_CHASE_PASS := 5043484153454f4b
POINTER_CHASE_MEMH_BYTES := $(shell expr $(POINTER_CHASE_BYTES) + 65536)
POINTER_CHASE_MEMH_WORDS := $(shell expr $(POINTER_CHASE_MEMH_BYTES) / 32)
POINTER_CHASE_MAX_CYCLES ?= 60000000
POINTER_CHASE_RAM_BYTES ?= 33554432
POINTER_CHASE_DDR3_BP_TYPE ?= $(BP_TYPE_DEFAULT)
POINTER_CHASE_DDR3_FETCH_ALT_LOOKASIDE ?= 3
POINTER_CHASE_DDR3_RETIRE_DEPTH ?= 16
POINTER_CHASE_DDR3_ISSUE_WINDOW ?= 1
POINTER_CHASE_DDR3_SPECULATION_WINDOW ?= 1
POINTER_CHASE_DDR3_POSTED_STORES ?= 1

A53_POINTER_CHASE_ELF := sim/a53/pointer-chase-$(POINTER_CHASE_TAG)-se.elf
A53_POINTER_CHASE_MAP := sim/a53/pointer-chase-$(POINTER_CHASE_TAG)-se.map
A53_POINTER_CHASE_DISASM := sim/a53/pointer-chase-$(POINTER_CHASE_TAG)-se.disasm
A53_POINTER_CHASE_OUTDIR ?= sim/a53/gem5-hpi-pointer-chase-$(POINTER_CHASE_TAG)
A53_POINTER_CHASE_STATS := $(A53_POINTER_CHASE_OUTDIR)/stats.txt
A53_POINTER_CHASE_REPORT := $(A53_POINTER_CHASE_OUTDIR)/report.txt

$(POINTER_CHASE_RING_S): tools/gen_multichase_ring.py $(OPENRV64_MAKEFILES)
	mkdir -p $(dir $@)
	$(PYTHON) tools/gen_multichase_ring.py $@ \
		--bytes $(POINTER_CHASE_BYTES) \
		--stride $(POINTER_CHASE_STRIDE) \
		--tlb-locality $(POINTER_CHASE_TLB_LOCALITY) \
		--seed $(POINTER_CHASE_SEED)

$(POINTER_CHASE_ELF): $(OPENRV64_MAKEFILES) \
		sw/multichase/pointer_chase.S $(POINTER_CHASE_RING_S) \
		sw/runtime/bare.S sw/runtime/c_start.inc \
		sw/multichase/openrv64-pointer-chase.ld
	mkdir -p $(dir $@)
	$(RISCV_CC) $(PREFETCH_ASFLAGS) \
		-Wa,--defsym,POINTER_CHASE_NODES=$(POINTER_CHASE_NODES) \
		-Wa,--defsym,POINTER_CHASE_STEPS=$(POINTER_CHASE_STEPS) \
		-Wl,--build-id=none,-Map,$(POINTER_CHASE_MAP) \
		-T sw/multichase/openrv64-pointer-chase.ld -o $@ \
		sw/runtime/bare.S sw/multichase/pointer_chase.S \
		$(POINTER_CHASE_RING_S)

$(POINTER_CHASE_BIN): $(POINTER_CHASE_ELF)
	$(RISCV_OBJCOPY) -O binary $< $@

$(POINTER_CHASE_DISASM): $(POINTER_CHASE_ELF)
	$(RISCV_OBJDUMP) -d -M no-aliases $< > $@

$(A53_POINTER_CHASE_ELF): $(OPENRV64_MAKEFILES) \
		sw/arm_a53/pointer_chase_se.S $(POINTER_CHASE_RING_S) \
		sw/arm_a53/coremark_loop_se.ld
	mkdir -p $(dir $@)
	$(AARCH64_CC) -mcpu=cortex-a53 -mabi=lp64 -nostdlib -nostartfiles \
		-static -no-pie \
		-Wa,--defsym,POINTER_CHASE_NODES=$(POINTER_CHASE_NODES) \
		-Wa,--defsym,POINTER_CHASE_STEPS=$(POINTER_CHASE_STEPS) \
		-Wl,--build-id=none,--gc-sections,-Map,$(A53_POINTER_CHASE_MAP) \
		-T sw/arm_a53/coremark_loop_se.ld -o $@ \
		sw/arm_a53/pointer_chase_se.S $(POINTER_CHASE_RING_S)

$(A53_POINTER_CHASE_DISASM): $(A53_POINTER_CHASE_ELF)
	$(AARCH64_OBJDUMP) -d $< > $@

sw-pointer-chase: $(POINTER_CHASE_ELF) $(POINTER_CHASE_BIN) \
		$(POINTER_CHASE_DISASM)

sw-pointer-chase-a53-gem5: $(A53_POINTER_CHASE_ELF) \
		$(A53_POINTER_CHASE_DISASM)

bench-pointer-chase-ddr3: $(POINTER_CHASE_ELF)
	test -n "$(POINTER_CHASE_MEASURE_END)"
	$(MAKE) sim-core-3p-icx-l2 \
		AXI_3P_PERF_ELF=$(POINTER_CHASE_ELF) \
		AXI_3P_PERF_BIN=sim/pointer-chase-$(POINTER_CHASE_TAG)-ddr3-bench.bin \
		AXI_3P_PERF_MEMH=sim/pointer-chase-$(POINTER_CHASE_TAG)-ddr3-bench.memh \
		AXI_3P_PERF_MEMH_BYTES=$(POINTER_CHASE_MEMH_BYTES) \
		CORE_3P_ICX_L2_MEMH=sim/pointer-chase-$(POINTER_CHASE_TAG)-ddr3-bench.memh \
		CORE_3P_ICX_L2_MEMH_WORDS=$(POINTER_CHASE_MEMH_WORDS) \
		CORE_3P_ICX_L2_ARGS="+done_pc=$(POINTER_CHASE_MEASURE_END) +require_timed_memory" \
		CORE_3P_ICX_L2_MAX_CYCLES=$(POINTER_CHASE_MAX_CYCLES) \
		CORE_3P_ICX_L2_RAM_BYTES=$(POINTER_CHASE_RAM_BYTES) \
		CORE_3P_ICX_L2_BP_TYPE=$(POINTER_CHASE_DDR3_BP_TYPE) \
		CORE_3P_ICX_L2_MODE=$(POINTER_CHASE_DDR3_FETCH_ALT_LOOKASIDE) \
		CORE_3P_ICX_L2_RETIRE_DEPTH=$(POINTER_CHASE_DDR3_RETIRE_DEPTH) \
		CORE_3P_ICX_L2_ISSUE_WINDOW=$(POINTER_CHASE_DDR3_ISSUE_WINDOW) \
		CORE_3P_ICX_L2_SPECULATION_WINDOW=$(POINTER_CHASE_DDR3_SPECULATION_WINDOW) \
		CORE_3P_ICX_L2_POSTED_STORES=$(POINTER_CHASE_DDR3_POSTED_STORES) \
		CORE_3P_ICX_L2_L1D_PREFETCH_ENABLE=$(PREFETCH_L1D_ENABLE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_STREAMS=$(PREFETCH_L1D_STREAMS) \
		CORE_3P_ICX_L2_L1D_PREFETCH_DISTANCE=$(PREFETCH_L1D_DISTANCE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE=$(PREFETCH_L1D_ADAPTIVE_ENABLE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_MAX_DISTANCE=$(PREFETCH_L1D_MAX_DISTANCE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_QUEUE_LINES=$(PREFETCH_L1D_QUEUE_LINES) \
		CORE_3P_ICX_L2_L1D_PREFETCH_OUTSTANDING=$(PREFETCH_L1D_OUTSTANDING) \
		CORE_3P_ICX_L2_L1D_PREFETCH_DEMAND_RESERVE=$(PREFETCH_L1D_DEMAND_RESERVE) \
		CORE_3P_ICX_L2_MEMORY_TIMING_MODEL=0 \
		CORE_3P_ICX_L2_DDR3=1

sim-pointer-chase-ddr3: $(POINTER_CHASE_ELF)
	$(MAKE) sim-core-3p-icx-l2 \
		AXI_3P_PERF_ELF=$(POINTER_CHASE_ELF) \
		AXI_3P_PERF_BIN=sim/pointer-chase-$(POINTER_CHASE_TAG)-ddr3-check.bin \
		AXI_3P_PERF_MEMH=sim/pointer-chase-$(POINTER_CHASE_TAG)-ddr3-check.memh \
		AXI_3P_PERF_MEMH_BYTES=$(POINTER_CHASE_MEMH_BYTES) \
		CORE_3P_ICX_L2_MEMH=sim/pointer-chase-$(POINTER_CHASE_TAG)-ddr3-check.memh \
		CORE_3P_ICX_L2_MEMH_WORDS=$(POINTER_CHASE_MEMH_WORDS) \
		CORE_3P_ICX_L2_ARGS="+expect_a0=$(POINTER_CHASE_PASS) +require_timed_memory" \
		CORE_3P_ICX_L2_MAX_CYCLES=$(POINTER_CHASE_MAX_CYCLES) \
		CORE_3P_ICX_L2_RAM_BYTES=$(POINTER_CHASE_RAM_BYTES) \
		CORE_3P_ICX_L2_BP_TYPE=$(POINTER_CHASE_DDR3_BP_TYPE) \
		CORE_3P_ICX_L2_MODE=$(POINTER_CHASE_DDR3_FETCH_ALT_LOOKASIDE) \
		CORE_3P_ICX_L2_RETIRE_DEPTH=$(POINTER_CHASE_DDR3_RETIRE_DEPTH) \
		CORE_3P_ICX_L2_ISSUE_WINDOW=$(POINTER_CHASE_DDR3_ISSUE_WINDOW) \
		CORE_3P_ICX_L2_SPECULATION_WINDOW=$(POINTER_CHASE_DDR3_SPECULATION_WINDOW) \
		CORE_3P_ICX_L2_POSTED_STORES=$(POINTER_CHASE_DDR3_POSTED_STORES) \
		CORE_3P_ICX_L2_L1D_PREFETCH_ENABLE=$(PREFETCH_L1D_ENABLE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_STREAMS=$(PREFETCH_L1D_STREAMS) \
		CORE_3P_ICX_L2_L1D_PREFETCH_DISTANCE=$(PREFETCH_L1D_DISTANCE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE=$(PREFETCH_L1D_ADAPTIVE_ENABLE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_MAX_DISTANCE=$(PREFETCH_L1D_MAX_DISTANCE) \
		CORE_3P_ICX_L2_L1D_PREFETCH_QUEUE_LINES=$(PREFETCH_L1D_QUEUE_LINES) \
		CORE_3P_ICX_L2_L1D_PREFETCH_OUTSTANDING=$(PREFETCH_L1D_OUTSTANDING) \
		CORE_3P_ICX_L2_L1D_PREFETCH_DEMAND_RESERVE=$(PREFETCH_L1D_DEMAND_RESERVE) \
		CORE_3P_ICX_L2_MEMORY_TIMING_MODEL=0 \
		CORE_3P_ICX_L2_DDR3=1

sim-pointer-chase-a53-gem5: sw-pointer-chase-a53-gem5
	test -x $(GEM5_AARCH64)
	test -f $(GEM5_A53_CONFIG)
	$(GEM5_AARCH64) -d $(A53_POINTER_CHASE_OUTDIR) \
		$(GEM5_A53_CONFIG) --cpu=hpi --cpu-freq=1GHz \
		--num-cores=1 --mem-type=DDR3_1600_8x8 --mem-channels=1 \
		--mem-size=128MiB \
		-P 'system.cpu_cluster.cpus[0].enableIdling=False' \
		$(abspath $(A53_POINTER_CHASE_ELF))
	$(PYTHON) tools/gem5_hpi_pointer_chase_report.py \
		$(A53_POINTER_CHASE_STATS) \
		--bytes $(POINTER_CHASE_BYTES) \
		--stride $(POINTER_CHASE_STRIDE) \
		--tlb-locality $(POINTER_CHASE_TLB_LOCALITY) \
		--steps $(POINTER_CHASE_STEPS) \
		--seed $(POINTER_CHASE_SEED) \
		--output $(A53_POINTER_CHASE_REPORT)

.PHONY: sw-pointer-chase sw-pointer-chase-a53-gem5 \
	bench-pointer-chase-ddr3 sim-pointer-chase-ddr3 \
	sim-pointer-chase-a53-gem5
