# Integer STREAM workload and A53 comparison targets.

sw-stream: $(STREAM_ELF) $(STREAM_BIN) $(STREAM_DISASM)

sw-stream-suite:
	$(MAKE) sw-stream STREAM_KERNEL=copy
	$(MAKE) sw-stream STREAM_KERNEL=scale
	$(MAKE) sw-stream STREAM_KERNEL=add
	$(MAKE) sw-stream STREAM_KERNEL=triad

bench-stream: $(STREAM_ELF)
	test -n "$(STREAM_MEASURE_END)"
	$(MAKE) sim-prefetch-3p-perf \
		AXI_3P_PERF_PIPELINE_TRACE=$(PREFETCH_PIPELINE_TRACE) \
		AXI_3P_PERF_ELF=$(STREAM_ELF) \
		AXI_3P_PERF_BIN=sim/stream-$(STREAM_TAG)-bench.bin \
		AXI_3P_PERF_MEMH=sim/stream-$(STREAM_TAG)-bench.memh \
		AXI_3P_PERF_MEMH_BYTES=$(STREAM_MEMH_BYTES) \
		AXI_3P_PERF_MAX_CYCLES=$(STREAM_MAX_CYCLES) \
		AXI_3P_PERF_ARGS="+memh_words=$(STREAM_MEMH_WORDS) +done_pc=$(STREAM_MEASURE_END)" \
		AXI_3P_TRACE_CSV=sim/stream-$(STREAM_TAG)-bench-trace.csv \
		AXI_3P_TRACE_REPORT=sim/stream-$(STREAM_TAG)-bench-pipeline.txt

bench-stream-suite:
	$(MAKE) bench-stream STREAM_KERNEL=copy
	$(MAKE) bench-stream STREAM_KERNEL=scale
	$(MAKE) bench-stream STREAM_KERNEL=add
	$(MAKE) bench-stream STREAM_KERNEL=triad

sim-stream: $(STREAM_ELF)
	$(MAKE) sim-prefetch-3p-perf \
		AXI_3P_PERF_PIPELINE_TRACE=$(PREFETCH_PIPELINE_TRACE) \
		AXI_3P_PERF_ELF=$(STREAM_ELF) \
		AXI_3P_PERF_BIN=sim/stream-$(STREAM_TAG)-check.bin \
		AXI_3P_PERF_MEMH=sim/stream-$(STREAM_TAG)-check.memh \
		AXI_3P_PERF_MEMH_BYTES=$(STREAM_MEMH_BYTES) \
		AXI_3P_PERF_MAX_CYCLES=$(STREAM_MAX_CYCLES) \
		AXI_3P_PERF_ARGS="+memh_words=$(STREAM_MEMH_WORDS) +expect_a0=$(STREAM_PASS)" \
		AXI_3P_TRACE_CSV=sim/stream-$(STREAM_TAG)-check-trace.csv \
		AXI_3P_TRACE_REPORT=sim/stream-$(STREAM_TAG)-check-pipeline.txt

sim-stream-suite:
	$(MAKE) sim-stream STREAM_KERNEL=copy
	$(MAKE) sim-stream STREAM_KERNEL=scale
	$(MAKE) sim-stream STREAM_KERNEL=add
	$(MAKE) sim-stream STREAM_KERNEL=triad

bench-stream-ddr3: $(STREAM_ELF)
	test -n "$(STREAM_MEASURE_END)"
	$(MAKE) sim-core-3p-ccx-l2 \
		AXI_3P_PERF_ELF=$(STREAM_ELF) \
		AXI_3P_PERF_BIN=sim/stream-$(STREAM_TAG)-ddr3-bench.bin \
		AXI_3P_PERF_MEMH=sim/stream-$(STREAM_TAG)-ddr3-bench.memh \
		AXI_3P_PERF_MEMH_BYTES=$(STREAM_MEMH_BYTES) \
		CORE_3P_CCX_L2_MEMH=sim/stream-$(STREAM_TAG)-ddr3-bench.memh \
		CORE_3P_CCX_L2_MEMH_WORDS=$(STREAM_MEMH_WORDS) \
		CORE_3P_CCX_L2_ARGS="+done_pc=$(STREAM_MEASURE_END) $(STREAM_TIMED_REQUIRE_ARGS)" \
		CORE_3P_CCX_L2_MAX_CYCLES=$(STREAM_MAX_CYCLES) \
		CORE_3P_CCX_L2_BP_TYPE=$(STREAM_DDR3_BP_TYPE) \
		CORE_3P_CCX_L2_MODE=$(STREAM_DDR3_FETCH_ALT_LOOKASIDE) \
		CORE_3P_CCX_L2_RETIRE_DEPTH=$(STREAM_DDR3_RETIRE_DEPTH) \
		CORE_3P_CCX_L2_ISSUE_WINDOW=$(STREAM_DDR3_ISSUE_WINDOW) \
		CORE_3P_CCX_L2_SPECULATION_WINDOW=$(STREAM_DDR3_SPECULATION_WINDOW) \
		CORE_3P_CCX_L2_POSTED_STORES=$(STREAM_DDR3_POSTED_STORES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ENABLE=$(PREFETCH_L1D_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_STREAMS=$(PREFETCH_L1D_STREAMS) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DISTANCE=$(PREFETCH_L1D_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE=$(PREFETCH_L1D_ADAPTIVE_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_MAX_DISTANCE=$(PREFETCH_L1D_MAX_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_QUEUE_LINES=$(PREFETCH_L1D_QUEUE_LINES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_OUTSTANDING=$(PREFETCH_L1D_OUTSTANDING) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DEMAND_RESERVE=$(PREFETCH_L1D_DEMAND_RESERVE) \
		CORE_3P_CCX_L2_MEMORY_TIMING_MODEL=$(STREAM_MEMORY_TIMING_MODEL) \
		CORE_3P_CCX_L2_DDR3=1

sim-stream-ddr3: $(STREAM_ELF)
	$(MAKE) sim-core-3p-ccx-l2 \
		AXI_3P_PERF_ELF=$(STREAM_ELF) \
		AXI_3P_PERF_BIN=sim/stream-$(STREAM_TAG)-ddr3-check.bin \
		AXI_3P_PERF_MEMH=sim/stream-$(STREAM_TAG)-ddr3-check.memh \
		AXI_3P_PERF_MEMH_BYTES=$(STREAM_MEMH_BYTES) \
		CORE_3P_CCX_L2_MEMH=sim/stream-$(STREAM_TAG)-ddr3-check.memh \
		CORE_3P_CCX_L2_MEMH_WORDS=$(STREAM_MEMH_WORDS) \
		CORE_3P_CCX_L2_ARGS="+expect_a0=$(STREAM_PASS) $(STREAM_TIMED_REQUIRE_ARGS)" \
		CORE_3P_CCX_L2_MAX_CYCLES=$(STREAM_MAX_CYCLES) \
		CORE_3P_CCX_L2_BP_TYPE=$(STREAM_DDR3_BP_TYPE) \
		CORE_3P_CCX_L2_MODE=$(STREAM_DDR3_FETCH_ALT_LOOKASIDE) \
		CORE_3P_CCX_L2_RETIRE_DEPTH=$(STREAM_DDR3_RETIRE_DEPTH) \
		CORE_3P_CCX_L2_ISSUE_WINDOW=$(STREAM_DDR3_ISSUE_WINDOW) \
		CORE_3P_CCX_L2_SPECULATION_WINDOW=$(STREAM_DDR3_SPECULATION_WINDOW) \
		CORE_3P_CCX_L2_POSTED_STORES=$(STREAM_DDR3_POSTED_STORES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ENABLE=$(PREFETCH_L1D_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_STREAMS=$(PREFETCH_L1D_STREAMS) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DISTANCE=$(PREFETCH_L1D_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE=$(PREFETCH_L1D_ADAPTIVE_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_MAX_DISTANCE=$(PREFETCH_L1D_MAX_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_QUEUE_LINES=$(PREFETCH_L1D_QUEUE_LINES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_OUTSTANDING=$(PREFETCH_L1D_OUTSTANDING) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DEMAND_RESERVE=$(PREFETCH_L1D_DEMAND_RESERVE) \
		CORE_3P_CCX_L2_MEMORY_TIMING_MODEL=$(STREAM_MEMORY_TIMING_MODEL) \
		CORE_3P_CCX_L2_DDR3=1

bench-stream-ddr3-vm: $(STREAM_VM_MEMH)
	test -n "$(STREAM_VM_MEASURE_END)"
	$(MAKE) sim-core-3p-ccx-l2 \
		CORE_3P_CCX_L2_MEMH=$(STREAM_VM_MEMH) \
		CORE_3P_CCX_L2_MEMH_WORDS=$(STREAM_VM_MEMH_WORDS) \
		CORE_3P_CCX_L2_ARGS="+done_pc=$(STREAM_VM_MEASURE_END) +require_sv39 $(STREAM_TIMED_REQUIRE_ARGS)" \
		CORE_3P_CCX_L2_MAX_CYCLES=$(STREAM_MAX_CYCLES) \
		CORE_3P_CCX_L2_BP_TYPE=$(STREAM_DDR3_BP_TYPE) \
		CORE_3P_CCX_L2_MODE=$(STREAM_DDR3_FETCH_ALT_LOOKASIDE) \
		CORE_3P_CCX_L2_RETIRE_DEPTH=$(STREAM_DDR3_RETIRE_DEPTH) \
		CORE_3P_CCX_L2_ISSUE_WINDOW=$(STREAM_DDR3_ISSUE_WINDOW) \
		CORE_3P_CCX_L2_SPECULATION_WINDOW=$(STREAM_DDR3_SPECULATION_WINDOW) \
		CORE_3P_CCX_L2_POSTED_STORES=$(STREAM_DDR3_POSTED_STORES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ENABLE=$(PREFETCH_L1D_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_STREAMS=$(PREFETCH_L1D_STREAMS) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DISTANCE=$(PREFETCH_L1D_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE=$(PREFETCH_L1D_ADAPTIVE_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_MAX_DISTANCE=$(PREFETCH_L1D_MAX_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_QUEUE_LINES=$(PREFETCH_L1D_QUEUE_LINES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_OUTSTANDING=$(PREFETCH_L1D_OUTSTANDING) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DEMAND_RESERVE=$(PREFETCH_L1D_DEMAND_RESERVE) \
		CORE_3P_CCX_L2_MEMORY_TIMING_MODEL=$(STREAM_MEMORY_TIMING_MODEL) \
		CORE_3P_CCX_L2_SPEC_LOAD_BASE=1073741824 \
		CORE_3P_CCX_L2_SPEC_LOAD_SIZE=262144 \
		CORE_3P_CCX_L2_DDR3=1

bench-stream-ddr3-vm-suite:
	$(MAKE) bench-stream-ddr3-vm STREAM_KERNEL=copy
	$(MAKE) bench-stream-ddr3-vm STREAM_KERNEL=scale
	$(MAKE) bench-stream-ddr3-vm STREAM_KERNEL=add
	$(MAKE) bench-stream-ddr3-vm STREAM_KERNEL=triad

sim-stream-ddr3-vm: $(STREAM_VM_MEMH)
	test -n "$(STREAM_VM_DONE)"
	$(MAKE) sim-core-3p-ccx-l2 \
		CORE_3P_CCX_L2_MEMH=$(STREAM_VM_MEMH) \
		CORE_3P_CCX_L2_MEMH_WORDS=$(STREAM_VM_MEMH_WORDS) \
		CORE_3P_CCX_L2_ARGS="+expect_a0=$(STREAM_PASS) +done_pc=$(STREAM_VM_DONE) +require_sv39 $(STREAM_TIMED_REQUIRE_ARGS)" \
		CORE_3P_CCX_L2_MAX_CYCLES=$(STREAM_MAX_CYCLES) \
		CORE_3P_CCX_L2_BP_TYPE=$(STREAM_DDR3_BP_TYPE) \
		CORE_3P_CCX_L2_MODE=$(STREAM_DDR3_FETCH_ALT_LOOKASIDE) \
		CORE_3P_CCX_L2_RETIRE_DEPTH=$(STREAM_DDR3_RETIRE_DEPTH) \
		CORE_3P_CCX_L2_ISSUE_WINDOW=$(STREAM_DDR3_ISSUE_WINDOW) \
		CORE_3P_CCX_L2_SPECULATION_WINDOW=$(STREAM_DDR3_SPECULATION_WINDOW) \
		CORE_3P_CCX_L2_POSTED_STORES=$(STREAM_DDR3_POSTED_STORES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ENABLE=$(PREFETCH_L1D_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_STREAMS=$(PREFETCH_L1D_STREAMS) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DISTANCE=$(PREFETCH_L1D_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_ADAPTIVE_ENABLE=$(PREFETCH_L1D_ADAPTIVE_ENABLE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_MAX_DISTANCE=$(PREFETCH_L1D_MAX_DISTANCE) \
		CORE_3P_CCX_L2_L1D_PREFETCH_QUEUE_LINES=$(PREFETCH_L1D_QUEUE_LINES) \
		CORE_3P_CCX_L2_L1D_PREFETCH_OUTSTANDING=$(PREFETCH_L1D_OUTSTANDING) \
		CORE_3P_CCX_L2_L1D_PREFETCH_DEMAND_RESERVE=$(PREFETCH_L1D_DEMAND_RESERVE) \
		CORE_3P_CCX_L2_MEMORY_TIMING_MODEL=$(STREAM_MEMORY_TIMING_MODEL) \
		CORE_3P_CCX_L2_SPEC_LOAD_BASE=1073741824 \
		CORE_3P_CCX_L2_SPEC_LOAD_SIZE=262144 \
		CORE_3P_CCX_L2_DDR3=1

sim-stream-ddr3-vm-suite:
	$(MAKE) sim-stream-ddr3-vm STREAM_KERNEL=copy
	$(MAKE) sim-stream-ddr3-vm STREAM_KERNEL=scale
	$(MAKE) sim-stream-ddr3-vm STREAM_KERNEL=add
	$(MAKE) sim-stream-ddr3-vm STREAM_KERNEL=triad

bench-stream-magic:
	$(MAKE) bench-stream-ddr3 \
		STREAM_MEMORY_TIMING_MODEL=1 \
		STREAM_TIMED_REQUIRE_ARGS=+require_timed_memory

sim-stream-magic:
	$(MAKE) sim-stream-ddr3 \
		STREAM_MEMORY_TIMING_MODEL=1 \
		STREAM_TIMED_REQUIRE_ARGS=+require_timed_memory

sw-stream-a53-gem5: $(A53_STREAM_ELF) $(A53_STREAM_DISASM)

sim-stream-a53-gem5: sw-stream-a53-gem5
	test -x $(GEM5_AARCH64)
	test -f $(GEM5_A53_CONFIG)
	$(GEM5_AARCH64) -d $(A53_STREAM_OUTDIR) \
		$(GEM5_A53_CONFIG) --cpu=hpi --cpu-freq=1GHz \
		--num-cores=1 --mem-type=DDR3_1600_8x8 --mem-channels=1 \
		--mem-size=128MiB \
		-P 'system.cpu_cluster.cpus[0].enableIdling=False' \
		$(abspath $(A53_STREAM_ELF))
	$(PYTHON) tools/gem5_hpi_stream_report.py $(A53_STREAM_STATS) \
		--kernel $(STREAM_KERNEL) --bytes $(STREAM_BYTES) \
		--output $(A53_STREAM_REPORT)
