`ifndef OPENRV64_TRACE_DEFS_V
`define OPENRV64_TRACE_DEFS_V

`define OPENRV64_TRACE_SCHEMA_VERSION 1

`define OPENRV64_TRACE_STAGE_IF  0
`define OPENRV64_TRACE_STAGE_ID  1
`define OPENRV64_TRACE_STAGE_EX  2
`define OPENRV64_TRACE_STAGE_MEM 3
`define OPENRV64_TRACE_STAGE_WB  4
`define OPENRV64_TRACE_STAGE_COUNT 5

`define OPENRV64_TRACE_EVENT_REDIRECT 0
`define OPENRV64_TRACE_EVENT_TRAP     1
`define OPENRV64_TRACE_EVENT_IRQ      2
`define OPENRV64_TRACE_EVENT_MRET     3
`define OPENRV64_TRACE_EVENT_SRET     4
`define OPENRV64_TRACE_EVENT_RESTART  5
`define OPENRV64_TRACE_EVENT_HALT     6
`define OPENRV64_TRACE_EVENT_RESET    7

`define OPENRV64_TRACE_STALL_RAW           0
`define OPENRV64_TRACE_STALL_WAW           1
`define OPENRV64_TRACE_STALL_SCOREBOARD    2
`define OPENRV64_TRACE_STALL_IF_MEMORY     3
`define OPENRV64_TRACE_STALL_DATA_MEMORY   4
`define OPENRV64_TRACE_STALL_EXECUTE       5
`define OPENRV64_TRACE_STALL_FRONTEND_HELD 6
`define OPENRV64_TRACE_STALL_SERIALIZING   7

`endif
