`timescale 1ns/1ps

// Intentionally no include guard: wrapper_2h.v and wrapper_4h.v each include
// this template with a distinct module name and fixed hart count.
module `OPENRV64_CCX_FIXED_MODULE #(
    parameter integer HART_ID_BASE = 0,
    parameter [`OPENRV64_CCX_ATTR_WIDTH-1:0] DEFAULT_ATTR =
        `OPENRV64_CCX_ATTR_NONE,
    parameter integer AXI_ADDR_WIDTH = `OPENRV64_AXI_ADDR_WIDTH,
    parameter integer AXI_DATA_WIDTH = `OPENRV64_AXI_DATA_WIDTH,
    parameter integer AXI_ID_WIDTH = `OPENRV64_AXI_ID_WIDTH,
    parameter [AXI_ID_WIDTH-1:0] AXI_ID = {AXI_ID_WIDTH{1'b1}}
) (
    input  wire clk_i,
    input  wire rst_ni,

    input  wire [`OPENRV64_CCX_FIXED_HARTS-1:0] core_mem_valid_i,
    output wire [`OPENRV64_CCX_FIXED_HARTS-1:0] core_mem_ready_o,
    input  wire [`OPENRV64_CCX_FIXED_HARTS-1:0] core_mem_write_i,
    input  wire [`OPENRV64_CCX_FIXED_HARTS*64-1:0] core_mem_addr_i,
    input  wire [`OPENRV64_CCX_FIXED_HARTS*64-1:0] core_mem_wdata_i,
    input  wire [`OPENRV64_CCX_FIXED_HARTS*8-1:0] core_mem_wstrb_i,
    output wire [`OPENRV64_CCX_FIXED_HARTS*64-1:0] core_mem_rdata_o,
    output wire [`OPENRV64_CCX_FIXED_HARTS-1:0] core_mem_error_o,

    output wire [AXI_ID_WIDTH-1:0]   m_axi_arid_o,
    output wire [AXI_ADDR_WIDTH-1:0] m_axi_araddr_o,
    output wire [7:0]                m_axi_arlen_o,
    output wire [2:0]                m_axi_arsize_o,
    output wire [1:0]                m_axi_arburst_o,
    output wire                      m_axi_arlock_o,
    output wire [3:0]                m_axi_arcache_o,
    output wire [2:0]                m_axi_arprot_o,
    output wire [3:0]                m_axi_arqos_o,
    output wire                      m_axi_arvalid_o,
    input  wire                      m_axi_arready_i,
    input  wire [AXI_ID_WIDTH-1:0]   m_axi_rid_i,
    input  wire [AXI_DATA_WIDTH-1:0] m_axi_rdata_i,
    input  wire [1:0]                m_axi_rresp_i,
    input  wire                      m_axi_rlast_i,
    input  wire                      m_axi_rvalid_i,
    output wire                      m_axi_rready_o,

    output wire [AXI_ID_WIDTH-1:0]   m_axi_awid_o,
    output wire [AXI_ADDR_WIDTH-1:0] m_axi_awaddr_o,
    output wire [7:0]                m_axi_awlen_o,
    output wire [2:0]                m_axi_awsize_o,
    output wire [1:0]                m_axi_awburst_o,
    output wire                      m_axi_awlock_o,
    output wire [3:0]                m_axi_awcache_o,
    output wire [2:0]                m_axi_awprot_o,
    output wire [3:0]                m_axi_awqos_o,
    output wire                      m_axi_awvalid_o,
    input  wire                      m_axi_awready_i,
    output wire [AXI_DATA_WIDTH-1:0] m_axi_wdata_o,
    output wire [(AXI_DATA_WIDTH/8)-1:0] m_axi_wstrb_o,
    output wire                      m_axi_wlast_o,
    output wire                      m_axi_wvalid_o,
    input  wire                      m_axi_wready_i,
    input  wire [AXI_ID_WIDTH-1:0]   m_axi_bid_i,
    input  wire [1:0]                m_axi_bresp_i,
    input  wire                      m_axi_bvalid_i,
    output wire                      m_axi_bready_o
);

    openrv64_ccx_protocol_wrapper_nh #(
        .NUM_HARTS(`OPENRV64_CCX_FIXED_HARTS),
        .HART_ID_BASE(HART_ID_BASE),
        .DEFAULT_ATTR(DEFAULT_ATTR),
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .AXI_ID(AXI_ID)
    ) u_wrapper (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .core_mem_valid_i(core_mem_valid_i),
        .core_mem_ready_o(core_mem_ready_o),
        .core_mem_write_i(core_mem_write_i),
        .core_mem_addr_i(core_mem_addr_i),
        .core_mem_wdata_i(core_mem_wdata_i),
        .core_mem_wstrb_i(core_mem_wstrb_i),
        .core_mem_rdata_o(core_mem_rdata_o),
        .core_mem_error_o(core_mem_error_o),
        .m_axi_arid_o(m_axi_arid_o),
        .m_axi_araddr_o(m_axi_araddr_o),
        .m_axi_arlen_o(m_axi_arlen_o),
        .m_axi_arsize_o(m_axi_arsize_o),
        .m_axi_arburst_o(m_axi_arburst_o),
        .m_axi_arlock_o(m_axi_arlock_o),
        .m_axi_arcache_o(m_axi_arcache_o),
        .m_axi_arprot_o(m_axi_arprot_o),
        .m_axi_arqos_o(m_axi_arqos_o),
        .m_axi_arvalid_o(m_axi_arvalid_o),
        .m_axi_arready_i(m_axi_arready_i),
        .m_axi_rid_i(m_axi_rid_i),
        .m_axi_rdata_i(m_axi_rdata_i),
        .m_axi_rresp_i(m_axi_rresp_i),
        .m_axi_rlast_i(m_axi_rlast_i),
        .m_axi_rvalid_i(m_axi_rvalid_i),
        .m_axi_rready_o(m_axi_rready_o),
        .m_axi_awid_o(m_axi_awid_o),
        .m_axi_awaddr_o(m_axi_awaddr_o),
        .m_axi_awlen_o(m_axi_awlen_o),
        .m_axi_awsize_o(m_axi_awsize_o),
        .m_axi_awburst_o(m_axi_awburst_o),
        .m_axi_awlock_o(m_axi_awlock_o),
        .m_axi_awcache_o(m_axi_awcache_o),
        .m_axi_awprot_o(m_axi_awprot_o),
        .m_axi_awqos_o(m_axi_awqos_o),
        .m_axi_awvalid_o(m_axi_awvalid_o),
        .m_axi_awready_i(m_axi_awready_i),
        .m_axi_wdata_o(m_axi_wdata_o),
        .m_axi_wstrb_o(m_axi_wstrb_o),
        .m_axi_wlast_o(m_axi_wlast_o),
        .m_axi_wvalid_o(m_axi_wvalid_o),
        .m_axi_wready_i(m_axi_wready_i),
        .m_axi_bid_i(m_axi_bid_i),
        .m_axi_bresp_i(m_axi_bresp_i),
        .m_axi_bvalid_i(m_axi_bvalid_i),
        .m_axi_bready_o(m_axi_bready_o)
    );

endmodule
