`timescale 1ns/1ps
`include "soc/bus/mem_map.v"
`include "core/backend/backend-defs.v"
`include "core/bus/bus-defs.v"
`include "core/exec/bp/defs.v"
`include "complex/protocol/defs.v"

// Fixed 4PF core boundary with a 256-bit AXI port and native ICX port.
//
// Unlike openrv64_top, this module has no backend or bus selector at its
// external boundary.  Elaboration always selects fetch_3w, the EX0/EX1/MEM
// backend, and the AXI-configured core bus.  L1I/L1D traffic uses native ICX;
// AXI remains available only for explicit cacheless-L1I mode.  The
// legacy blocking requester is tied off and is not part of this interface.
module openrv64_top_4pf #(
    parameter [63:0] RESET_VECTOR = `OPENRV64_SOC_RESET_VECTOR,
    parameter ENABLE_RV64M = 0,
    parameter ENABLE_RV64F = 1,
    parameter ENABLE_RV64D = 1,
    parameter ENABLE_PIPELINED_FP_MULTIPLY = 1,
    parameter integer HPM_COUNTERS = 8,
    parameter integer RETIRE_DEPTH = 16,
    parameter integer PHYS_REG_COUNT = `OPENRV64_PHYS_REG_COUNT,
    parameter integer PHYS_REG_ADDR_WIDTH =
        (PHYS_REG_COUNT < 1) ? 1 : $clog2(PHYS_REG_COUNT + 1),
    parameter [2:0] COMPLETION_FORWARD_MASK = 3'b000,
    parameter [2:0] BRANCH_COMPLETION_FORWARD_MASK = 3'b001,
    parameter ENABLE_FULL_FORWARDING = 0,
    parameter RELAX_WAW = 1,
    parameter RELAX_HAZARDS = 0,
    parameter FREE_BRANCHES = 0,
    parameter ENABLE_EQ_BRANCH_PAIRING = 1,
    parameter ENABLE_ISSUE_WINDOW = 1,
    parameter ENABLE_SPECULATION_WINDOW = 1,
    parameter REGISTER_ISSUE_SELECT = 0,
    parameter ENABLE_POSTED_STORES = 1,
    parameter ENABLE_ZICCLSM = 1,
    parameter integer LOAD_QUEUE_DEPTH = 4,
    parameter integer STORE_QUEUE_DEPTH = 4,
    parameter [63:0] STORE_FORWARD_BASE = `OPENRV64_SOC_MEMORY_BASE,
    parameter [63:0] STORE_FORWARD_SIZE = `OPENRV64_SOC_MEMORY_SIZE,
    parameter ENABLE_RV64A = 1,
    parameter ENABLE_L1I = 1,
    parameter ENABLE_L1D = 1,
    parameter integer L1I_CACHE_BYTES = 16 * 1024,
    parameter integer L1D_CACHE_BYTES = 16 * 1024,
    parameter [63:0] L1D_CACHEABLE_BASE = `OPENRV64_SOC_MEMORY_BASE,
    parameter [63:0] L1D_CACHEABLE_SIZE = `OPENRV64_SOC_MEMORY_SIZE,
    parameter integer L1D_FILL_BUFFER_LINES = 8,
    parameter integer L1D_DEMAND_MSHRS = 3,
    parameter integer L1D_STORE_BUFFER_LINES = 8,
    parameter integer L1D_PREFETCH_ENABLE = 1,
    parameter integer L1D_PREFETCH_MAX_STRIDE_LINES = 64,
    parameter integer L1D_PREFETCH_STREAMS = 2,
    parameter integer L1D_PREFETCH_DISTANCE = 1,
    parameter integer L1D_PREFETCH_ADAPTIVE_ENABLE = 1,
    parameter integer L1D_PREFETCH_MAX_DISTANCE = 4,
    parameter integer L1D_PREFETCH_QUEUE_LINES = 4,
    parameter integer L1D_PREFETCH_OUTSTANDING = 4,
    parameter integer L1D_PREFETCH_DEMAND_RESERVE = 2,
    parameter integer L1D_PREFETCH_PAGE_GATING = 1,
    parameter integer L1I_FILL_BUFFER_LINES = 8,
    parameter integer L1I_DEMAND_MSHRS = 4,
    parameter integer L2_TLB_ENTRIES = 256,
    parameter integer L2_TLB_WAYS = 4,
    parameter integer PTW_PTE_CACHE_ENTRIES = 64,
    parameter integer PTW_ICX_TIMEOUT_CYCLES = 65536,
    parameter [`OPENRV64_ICX_HART_ID_WIDTH-1:0] HART_ID =
        {`OPENRV64_ICX_HART_ID_WIDTH{1'b0}},
    parameter ENABLE_TRACE = 0,
    parameter ENABLE_PREDECODE_TARGETS = 1,
    parameter ENABLE_FETCH_CAROUSEL = 1,
    parameter ENABLE_FETCH_ALT_LOOKASIDE = 3,
    parameter ENABLE_FETCH_ALT_CONFIDENCE_GATE = 1,
    parameter [`OPENRV64_BP_TYPE_WIDTH-1:0] BP_TYPE = `OPENRV64_BP_DEFAULT,
    parameter BP_RAS_ENABLE = 1,
    parameter integer BP_RAS_DEPTH = 8,
    parameter integer BP_BIMODAL_ENTRIES = 32,
    parameter integer BP_BIMODAL_COUNTER_BITS = 3,
    parameter integer BP_BIMODAL_UPDATE_DEPTH = 4,
    parameter integer BP_GSHARE_ENTRIES = 256,
    parameter integer BP_GSHARE_COUNTER_BITS = 3,
    parameter integer BP_BTB_ENTRIES = 256,
    parameter integer BP_BTB_TAG_BITS = 16,
    parameter integer BP_INFLIGHT_DEPTH = 16
) (
    input  wire        clk,
    input  wire        rst_n,

    output wire [`OPENRV64_AXI_ID_WIDTH-1:0]   m_axi_arid,
    output wire [`OPENRV64_AXI_ADDR_WIDTH-1:0] m_axi_araddr,
    output wire [7:0]  m_axi_arlen,
    output wire [2:0]  m_axi_arsize,
    output wire [1:0]  m_axi_arburst,
    output wire        m_axi_arlock,
    output wire [3:0]  m_axi_arcache,
    output wire [2:0]  m_axi_arprot,
    output wire [3:0]  m_axi_arqos,
    output wire        m_axi_arvalid,
    input  wire        m_axi_arready,
    input  wire [`OPENRV64_AXI_ID_WIDTH-1:0]   m_axi_rid,
    input  wire [`OPENRV64_AXI_DATA_WIDTH-1:0] m_axi_rdata,
    input  wire [1:0]  m_axi_rresp,
    input  wire        m_axi_rlast,
    input  wire        m_axi_rvalid,
    output wire        m_axi_rready,

    output wire [`OPENRV64_AXI_ID_WIDTH-1:0]   m_axi_awid,
    output wire [`OPENRV64_AXI_ADDR_WIDTH-1:0] m_axi_awaddr,
    output wire [7:0]  m_axi_awlen,
    output wire [2:0]  m_axi_awsize,
    output wire [1:0]  m_axi_awburst,
    output wire        m_axi_awlock,
    output wire [3:0]  m_axi_awcache,
    output wire [2:0]  m_axi_awprot,
    output wire [3:0]  m_axi_awqos,
    output wire        m_axi_awvalid,
    input  wire        m_axi_awready,
    output wire [`OPENRV64_AXI_DATA_WIDTH-1:0] m_axi_wdata,
    output wire [`OPENRV64_AXI_STRB_WIDTH-1:0] m_axi_wstrb,
    output wire        m_axi_wlast,
    output wire        m_axi_wvalid,
    input  wire        m_axi_wready,
    input  wire [`OPENRV64_AXI_ID_WIDTH-1:0]   m_axi_bid,
    input  wire [1:0]  m_axi_bresp,
    input  wire        m_axi_bvalid,
    output wire        m_axi_bready,

    output wire        icx_req_valid,
    input  wire        icx_req_ready,
    output wire [`OPENRV64_ICX_HART_ID_WIDTH-1:0] icx_req_hart_id,
    output wire [`OPENRV64_ICX_TXN_ID_WIDTH-1:0] icx_req_txn_id,
    output wire [`OPENRV64_ICX_SOURCE_ID_WIDTH-1:0] icx_req_source_id,
    output wire [`OPENRV64_ICX_OP_WIDTH-1:0] icx_req_op,
    output wire        icx_req_lock,
    output wire [`OPENRV64_ICX_ORDER_WIDTH-1:0] icx_req_order,
    output wire [`OPENRV64_ICX_KIND_WIDTH-1:0] icx_req_kind,
    output wire [`OPENRV64_ICX_ATTR_WIDTH-1:0] icx_req_attr,
    output wire [2:0]  icx_req_size,
    output wire [63:0] icx_req_addr,
    output wire [`OPENRV64_ICX_BURST_LEN_WIDTH-1:0] icx_req_burst_len,
    output wire        icx_wdata_valid,
    input  wire        icx_wdata_ready,
    output wire [`OPENRV64_ICX_HART_ID_WIDTH-1:0] icx_wdata_hart_id,
    output wire [`OPENRV64_ICX_TXN_ID_WIDTH-1:0] icx_wdata_txn_id,
    output wire [`OPENRV64_ICX_SOURCE_ID_WIDTH-1:0] icx_wdata_source_id,
    output wire [`OPENRV64_ICX_BEAT_INDEX_WIDTH-1:0] icx_wdata_beat_index,
    output wire        icx_wdata_last,
    output wire [`OPENRV64_ICX_LINE_DATA_WIDTH-1:0] icx_wdata,
    output wire [`OPENRV64_ICX_LINE_STRB_WIDTH-1:0] icx_wstrb,
    input  wire        icx_resp_valid,
    output wire        icx_resp_ready,
    input  wire [`OPENRV64_ICX_HART_ID_WIDTH-1:0] icx_resp_hart_id,
    input  wire [`OPENRV64_ICX_TXN_ID_WIDTH-1:0] icx_resp_txn_id,
    input  wire [`OPENRV64_ICX_SOURCE_ID_WIDTH-1:0] icx_resp_source_id,
    input  wire [`OPENRV64_ICX_BEAT_INDEX_WIDTH-1:0] icx_resp_beat_index,
    input  wire        icx_resp_last,
    input  wire [`OPENRV64_ICX_LINE_DATA_WIDTH-1:0] icx_resp_rdata,
    input  wire        icx_resp_error,
    input  wire        icx_resp_sc_success,

    input  wire        irq_m_software,
    input  wire        irq_m_timer,
    input  wire        irq_m_external,
    input  wire        irq_s_software,
    input  wire        irq_s_timer,
    input  wire        irq_s_external,

    output wire [63:0] dbg_pc,
    output wire [31:0] dbg_instr,
    output wire        dbg_halted,
    output wire        wfi_sleep,

    output wire [63:0]  trace_cycle,
    output wire [4:0]   trace_valid,
    output wire [4:0]   trace_stall,
    output wire [4:0]   trace_flush,
    output wire [4:0]   trace_advance,
    output wire [319:0] trace_ids,
    output wire [319:0] trace_pcs,
    output wire [159:0] trace_instrs,
    output wire [7:0]   trace_events,
    output wire [7:0]   trace_stall_causes,
    output wire         trace_retire_valid,
    output wire         trace_retire_arch,
    output wire         trace_retire_exception,
    output wire [4:0]   trace_retire_cause,
    output wire [63:0]  trace_retire_next_pc,
    output wire         trace_retire_rd_write,
    output wire [4:0]   trace_retire_rd,
    output wire [63:0]  trace_retire_wdata
);

    wire        unused_mem_valid;
    wire        unused_mem_write;
    wire [63:0] unused_mem_addr;
    wire [63:0] unused_mem_wdata;
    wire [7:0]  unused_mem_wstrb;

    openrv64_rv64_top_4pf #(
        .RESET_VECTOR(RESET_VECTOR),
        .BUS_CONFIG(`OPENRV64_BUS_AXI),
        .ENABLE_RV64M(ENABLE_RV64M),
        .ENABLE_RV64F(ENABLE_RV64F),
        .ENABLE_RV64D(ENABLE_RV64D),
        .ENABLE_PIPELINED_FP_MULTIPLY(ENABLE_PIPELINED_FP_MULTIPLY),
        .HPM_COUNTERS(HPM_COUNTERS),
        .RETIRE_DEPTH(RETIRE_DEPTH),
        .PHYS_REG_COUNT(PHYS_REG_COUNT),
        .PHYS_REG_ADDR_WIDTH(PHYS_REG_ADDR_WIDTH),
        .COMPLETION_FORWARD_MASK(COMPLETION_FORWARD_MASK),
        .BRANCH_COMPLETION_FORWARD_MASK(BRANCH_COMPLETION_FORWARD_MASK),
        .ENABLE_FULL_FORWARDING(ENABLE_FULL_FORWARDING),
        .RELAX_WAW(RELAX_WAW),
        .RELAX_HAZARDS(RELAX_HAZARDS),
        .FREE_BRANCHES(FREE_BRANCHES),
        .ENABLE_EQ_BRANCH_PAIRING(ENABLE_EQ_BRANCH_PAIRING),
        .ENABLE_ISSUE_WINDOW(ENABLE_ISSUE_WINDOW),
        .ENABLE_SPECULATION_WINDOW(ENABLE_SPECULATION_WINDOW),
        .REGISTER_ISSUE_SELECT(REGISTER_ISSUE_SELECT),
        .ENABLE_POSTED_STORES(ENABLE_POSTED_STORES),
        .ENABLE_ZICCLSM(ENABLE_ZICCLSM),
        .LOAD_QUEUE_DEPTH(LOAD_QUEUE_DEPTH),
        .STORE_QUEUE_DEPTH(STORE_QUEUE_DEPTH),
        .STORE_FORWARD_BASE(STORE_FORWARD_BASE),
        .STORE_FORWARD_SIZE(STORE_FORWARD_SIZE),
        .ENABLE_RV64A(ENABLE_RV64A),
        .ENABLE_L1I(ENABLE_L1I),
        .ENABLE_L1D(ENABLE_L1D),
        .ENABLE_L1D_COHERENCE_PROBES(1'b0),
        .ENABLE_COHERENT_ATOMICS(1'b0),
        .L1I_CACHE_BYTES(L1I_CACHE_BYTES),
        .L1D_CACHE_BYTES(L1D_CACHE_BYTES),
        .L1D_CACHEABLE_BASE(L1D_CACHEABLE_BASE),
        .L1D_CACHEABLE_SIZE(L1D_CACHEABLE_SIZE),
        .L1D_FILL_BUFFER_LINES(L1D_FILL_BUFFER_LINES),
        .L1D_DEMAND_MSHRS(L1D_DEMAND_MSHRS),
        .L1D_STORE_BUFFER_LINES(L1D_STORE_BUFFER_LINES),
        .L1D_PREFETCH_ENABLE(L1D_PREFETCH_ENABLE),
        .L1D_PREFETCH_MAX_STRIDE_LINES(
            L1D_PREFETCH_MAX_STRIDE_LINES),
        .L1D_PREFETCH_STREAMS(L1D_PREFETCH_STREAMS),
        .L1D_PREFETCH_DISTANCE(L1D_PREFETCH_DISTANCE),
        .L1D_PREFETCH_ADAPTIVE_ENABLE(
            L1D_PREFETCH_ADAPTIVE_ENABLE),
        .L1D_PREFETCH_MAX_DISTANCE(L1D_PREFETCH_MAX_DISTANCE),
        .L1D_PREFETCH_QUEUE_LINES(L1D_PREFETCH_QUEUE_LINES),
        .L1D_PREFETCH_OUTSTANDING(L1D_PREFETCH_OUTSTANDING),
        .L1D_PREFETCH_DEMAND_RESERVE(
            L1D_PREFETCH_DEMAND_RESERVE),
        .L1D_PREFETCH_PAGE_GATING(L1D_PREFETCH_PAGE_GATING),
        .L1I_FILL_BUFFER_LINES(L1I_FILL_BUFFER_LINES),
        .L1I_DEMAND_MSHRS(L1I_DEMAND_MSHRS),
        .L2_TLB_ENTRIES(L2_TLB_ENTRIES),
        .L2_TLB_WAYS(L2_TLB_WAYS),
        .PTW_PTE_CACHE_ENTRIES(PTW_PTE_CACHE_ENTRIES),
        .PTW_ICX_TIMEOUT_CYCLES(PTW_ICX_TIMEOUT_CYCLES),
        .HART_ID(HART_ID),
        .ENABLE_TRACE(ENABLE_TRACE),
        .ENABLE_PREDECODE_TARGETS(ENABLE_PREDECODE_TARGETS),
        .ENABLE_FETCH_CAROUSEL(ENABLE_FETCH_CAROUSEL),
        .ENABLE_FETCH_ALT_LOOKASIDE(ENABLE_FETCH_ALT_LOOKASIDE),
        .ENABLE_FETCH_ALT_CONFIDENCE_GATE(
            ENABLE_FETCH_ALT_CONFIDENCE_GATE),
        .BP_TYPE(BP_TYPE),
        .BP_RAS_ENABLE(BP_RAS_ENABLE),
        .BP_RAS_DEPTH(BP_RAS_DEPTH),
        .BP_BIMODAL_ENTRIES(BP_BIMODAL_ENTRIES),
        .BP_BIMODAL_COUNTER_BITS(BP_BIMODAL_COUNTER_BITS),
        .BP_BIMODAL_UPDATE_DEPTH(BP_BIMODAL_UPDATE_DEPTH),
        .BP_GSHARE_ENTRIES(BP_GSHARE_ENTRIES),
        .BP_GSHARE_COUNTER_BITS(BP_GSHARE_COUNTER_BITS),
        .BP_BTB_ENTRIES(BP_BTB_ENTRIES),
        .BP_BTB_TAG_BITS(BP_BTB_TAG_BITS),
        .BP_INFLIGHT_DEPTH(BP_INFLIGHT_DEPTH)
    ) u_core (
        .clk(clk), .rst_n(rst_n),
        .mem_valid(unused_mem_valid), .mem_ready(1'b0),
        .mem_write(unused_mem_write), .mem_addr(unused_mem_addr),
        .mem_wdata(unused_mem_wdata), .mem_wstrb(unused_mem_wstrb),
        .mem_rdata(64'd0), .mem_error(1'b0),
        .pair512_req_valid(), .pair512_req_ready(1'b0),
        .pair512_req_predicted_addr(),
        .pair512_req_unpredicted_addr(),
        .pair512_resp_valid(1'b0),
        .pair512_resp_predicted_addr(64'd0),
        .pair512_resp_predicted_data(
            {`OPENRV64_AXI_DATA_WIDTH{1'b0}}),
        .pair512_resp_unpredicted_addr(64'd0),
        .pair512_resp_unpredicted_data(
            {`OPENRV64_AXI_DATA_WIDTH{1'b0}}),
        .pair1024_req_valid(), .pair1024_req_ready(1'b0),
        .pair1024_req_predicted_addr(),
        .pair1024_req_unpredicted_addr(),
        .pair1024_resp_valid(1'b0),
        .pair1024_resp_predicted_addr(64'd0),
        .pair1024_resp_predicted_data(
            {`OPENRV64_ICX_LINE_DATA_WIDTH{1'b0}}),
        .pair1024_resp_unpredicted_addr(64'd0),
        .pair1024_resp_unpredicted_data(
            {`OPENRV64_ICX_LINE_DATA_WIDTH{1'b0}}),
        .m_axi_arid(m_axi_arid), .m_axi_araddr(m_axi_araddr),
        .m_axi_arlen(m_axi_arlen), .m_axi_arsize(m_axi_arsize),
        .m_axi_arburst(m_axi_arburst), .m_axi_arlock(m_axi_arlock),
        .m_axi_arcache(m_axi_arcache), .m_axi_arprot(m_axi_arprot),
        .m_axi_arqos(m_axi_arqos), .m_axi_arvalid(m_axi_arvalid),
        .m_axi_arready(m_axi_arready), .m_axi_rid(m_axi_rid),
        .m_axi_rdata(m_axi_rdata), .m_axi_rresp(m_axi_rresp),
        .m_axi_rlast(m_axi_rlast), .m_axi_rvalid(m_axi_rvalid),
        .m_axi_rready(m_axi_rready),
        .m_axi_awid(m_axi_awid), .m_axi_awaddr(m_axi_awaddr),
        .m_axi_awlen(m_axi_awlen), .m_axi_awsize(m_axi_awsize),
        .m_axi_awburst(m_axi_awburst), .m_axi_awlock(m_axi_awlock),
        .m_axi_awcache(m_axi_awcache), .m_axi_awprot(m_axi_awprot),
        .m_axi_awqos(m_axi_awqos), .m_axi_awvalid(m_axi_awvalid),
        .m_axi_awready(m_axi_awready), .m_axi_wdata(m_axi_wdata),
        .m_axi_wstrb_axi(m_axi_wstrb), .m_axi_wlast(m_axi_wlast),
        .m_axi_wvalid(m_axi_wvalid), .m_axi_wready(m_axi_wready),
        .m_axi_bid(m_axi_bid), .m_axi_bresp(m_axi_bresp),
        .m_axi_bvalid(m_axi_bvalid), .m_axi_bready(m_axi_bready),
        .icx_req_valid(icx_req_valid),
        .icx_req_ready(icx_req_ready),
        .icx_req_hart_id(icx_req_hart_id),
        .icx_req_txn_id(icx_req_txn_id),
        .icx_req_source_id(icx_req_source_id),
        .icx_req_op(icx_req_op),
        .icx_req_lock(icx_req_lock),
        .icx_req_order(icx_req_order),
        .icx_req_kind(icx_req_kind),
        .icx_req_attr(icx_req_attr),
        .icx_req_size(icx_req_size),
        .icx_req_addr(icx_req_addr),
        .icx_req_burst_len(icx_req_burst_len),
        .icx_wdata_valid(icx_wdata_valid),
        .icx_wdata_ready(icx_wdata_ready),
        .icx_wdata_hart_id(icx_wdata_hart_id),
        .icx_wdata_txn_id(icx_wdata_txn_id),
        .icx_wdata_source_id(icx_wdata_source_id),
        .icx_wdata_beat_index(icx_wdata_beat_index),
        .icx_wdata_last(icx_wdata_last),
        .icx_wdata(icx_wdata),
        .icx_wstrb(icx_wstrb),
        .icx_resp_valid(icx_resp_valid),
        .icx_resp_ready(icx_resp_ready),
        .icx_resp_hart_id(icx_resp_hart_id),
        .icx_resp_txn_id(icx_resp_txn_id),
        .icx_resp_source_id(icx_resp_source_id),
        .icx_resp_beat_index(icx_resp_beat_index),
        .icx_resp_last(icx_resp_last),
        .icx_resp_rdata(icx_resp_rdata),
        .icx_resp_error(icx_resp_error),
        .icx_resp_sc_success(icx_resp_sc_success),
        .l1d_probe_valid_i(1'b0),
        .l1d_probe_ready_o(),
        .l1d_probe_addr_i(64'd0),
        .coherent_reservation_clear_i(1'b0),
        .irq_m_software(irq_m_software), .irq_m_timer(irq_m_timer),
        .irq_m_external(irq_m_external),
        .irq_s_software(irq_s_software), .irq_s_timer(irq_s_timer),
        .irq_s_external(irq_s_external),
        .dbg_pc(dbg_pc), .dbg_instr(dbg_instr), .dbg_halted(dbg_halted),
        .wfi_sleep_o(wfi_sleep),
        .trace_cycle(trace_cycle), .trace_valid(trace_valid),
        .trace_stall(trace_stall), .trace_flush(trace_flush),
        .trace_advance(trace_advance), .trace_ids(trace_ids),
        .trace_pcs(trace_pcs), .trace_instrs(trace_instrs),
        .trace_events(trace_events),
        .trace_stall_causes(trace_stall_causes),
        .trace_retire_valid(trace_retire_valid),
        .trace_retire_arch(trace_retire_arch),
        .trace_retire_exception(trace_retire_exception),
        .trace_retire_cause(trace_retire_cause),
        .trace_retire_next_pc(trace_retire_next_pc),
        .trace_retire_rd_write(trace_retire_rd_write),
        .trace_retire_rd(trace_retire_rd),
        .trace_retire_wdata(trace_retire_wdata)
    );

`ifndef SYNTHESIS
    always @(posedge clk) begin
        if (rst_n && (unused_mem_valid || unused_mem_write ||
                      (|unused_mem_addr) || (|unused_mem_wdata) ||
                      (|unused_mem_wstrb)))
            $fatal(1, "openrv64_top_4pf: generic bus active in AXI geometry");
    end
`endif

endmodule
