`ifndef OPENRV64_EXCEPT_DEFS_V
`define OPENRV64_EXCEPT_DEFS_V

`define RV64_EXCEPT_CAUSE_WIDTH 5
`define RV64_EXCEPT_CAUSE_INSTR_ADDR_MISALIGNED 5'd0
`define RV64_EXCEPT_CAUSE_INSTR_ACCESS_FAULT 5'd1
`define RV64_EXCEPT_CAUSE_ILLEGAL_INSTR 5'd2
`define RV64_EXCEPT_CAUSE_BREAKPOINT 5'd3
`define RV64_EXCEPT_CAUSE_LOAD_ADDR_MISALIGNED 5'd4
`define RV64_EXCEPT_CAUSE_LOAD_ACCESS_FAULT 5'd5
`define RV64_EXCEPT_CAUSE_STORE_ADDR_MISALIGNED 5'd6
`define RV64_EXCEPT_CAUSE_STORE_ACCESS_FAULT 5'd7
`define RV64_EXCEPT_CAUSE_ECALL_U 5'd8
`define RV64_EXCEPT_CAUSE_ECALL_S 5'd9
`define RV64_EXCEPT_CAUSE_ECALL_M 5'd11
`define RV64_EXCEPT_CAUSE_INSTR_PAGE_FAULT 5'd12
`define RV64_EXCEPT_CAUSE_LOAD_PAGE_FAULT 5'd13
`define RV64_EXCEPT_CAUSE_STORE_PAGE_FAULT 5'd15

`endif
