name: openrv64-rv64ima
compiler_exe: riscv64-elf-gcc
objdump_exe: riscv64-elf-objdump
ref_model_exe: sail_riscv_sim
udb_config: openrv64-rv64ima.yaml
linker_script: ../link.ld
dut_include_dir: .
include_priv_tests: true
